export const locales = [
  'tr', 'fr', 'de', 'ru', 'nl', 'it', 'pt', 'es', 'th', 'sv', 'id', 'ja',
  'pl', 'cs', 'no', 'ar', 'da', 'he', 'uk', 'vi', 'ms', 'hi',
] as const;

export type Locale = (typeof locales)[number];

export type LocaleCopy = {
  name: string;
  nativeName: string;
  ogLocale: string;
  nav: { plan: string; features: string; guides: string; faq: string; download: string };
  hero: { badge: string; title: string; body: string; primary: string; secondary: string };
  stats: [string, string, string];
  proof: { title: string; body: string }[];
  plan: { eyebrow: string; title: string; body: string; steps: string[] };
  stories: { eyebrow: string; title: string; body: string; points: string[] }[];
  trust: { eyebrow: string; title: string; body: string; cards: { title: string; body: string }[] };
  guides: { eyebrow: string; title: string; body: string; action: string; articles: { title: string; body: string }[] };
  faq: { eyebrow: string; title: string; items: { question: string; answer: string }[] };
  cta: { badge: string; title: string; body: string; action: string };
  footer: string;
};

const englishGuideTitles = [
  'Baby Nap Schedule by Age',
  'Newborn Sleep Schedule',
  '4 Month Old Sleep Schedule',
  'Baby Feeding Schedule',
  'Wake Windows by Age',
  'How to Survive Night Wakings',
];

export const localeCopy = {
  tr: {
    name: 'Turkish', nativeName: 'Türkçe', ogLocale: 'tr_TR',
    nav: { plan: 'Plan', features: 'Özellikler', guides: 'Rehberler', faq: 'SSS', download: 'Uygulamayı indir' },
    hero: { badge: 'Bebek uyku takip ve yapay zeka programı', title: 'Bebeğinizin uykusunu sonunda anlayın.', body: 'Yorix, çocuğunuzun ritmini öğrenir; uykuları, uyanıklık pencerelerini, beslenmeyi, büyümeyi ve günlük bakımı gerçek aile hayatına uyum sağlayan bir plana dönüştürür.', primary: 'Sonraki uykuyu planla', secondary: 'Uyku rehberlerini oku' },
    stats: ['dil', 'rutininizde reklam', 'yapay zeka koçu'],
    proof: [{ title: 'Kişisel uyku planı', body: 'Sonraki uyku ve yatış saati gün değiştiğinde uyum sağlar.' }, { title: '7/24 yapay zeka uyku koçu', body: 'Uyanıklık pencereleri, kısa uykular ve rutinler hakkında sorun.' }, { title: 'Gizlilik öncelikli', body: 'Verileriniz size aittir. Kişisel verilerinizi satmayız.' }],
    plan: { eyebrow: 'Bebeğinizin bir planı var', title: 'Uyku işaretlerinden net bir sonraki adıma.', body: 'Yorix, yorgun ebeveynlerin sorusuna odaklanır: Bebeğim bir sonraki ne zaman uyumalı? Gün ilerledikçe plan esnek kalır.', steps: ['Herkes için çalışan bir rutin oluşturun', 'Yatmadan önce aşırı yorulmayı önleyin', 'Gerçek uyku, beslenme ve bakım düzenlerini öğrenin'] },
    stories: [{ eyebrow: 'Akıllı günlük plan', title: 'Bebeğinizin bir sonraki ne zaman uyuması gerektiğini bilin.', body: 'Yorix, şekerlemeleri, uyanıklık pencerelerini ve yatış saatini takip eder; gün değiştiğinde esnek planı günceller.', points: ['Uyarlanabilir uyanıklık pencereleri', 'Kısa uyku sonrası toparlanma', 'Güne göre değişen yatış saati'] }, { eyebrow: 'Sadece kayıt değil, ilerleme', title: 'Uyku, beslenme, büyüme ve bakım kalıplarını görün.', body: 'Günlük kayıtlar anlaşılır haftalık içgörülere dönüşür. Uyku, emzirme, bez, yürüyüş, banyo, oyun, boy ve kiloyu tek bir zaman çizelgesinde takip edin.', points: ['Uyku ve beslenme trendleri', 'WHO büyüme persentilleri', 'Paylaşılan bakım geçmişi'] }, { eyebrow: 'Yapay zeka uyku koçu', title: 'Googlelamak için fazla yorgun olduğunuz soruyu sorun.', body: 'Yorix; kısa uykular, gece uyanmaları, uyku geçişleri, yatma mücadeleleri ve günlük bakım sorularında yardımcı olur.', points: ['Uyku okulu', 'Rutin etkenleri', 'Bugünün planı'] }, { eyebrow: 'Uyku sesleri', title: 'Tanıdık gelen bir uyku ortamı oluşturun.', body: 'Beyaz, pembe ve kahverengi gürültü; yağmur, okyanus, kalp atışı ve uyku zamanlayıcılı hikayelerle sakin bir akşam rutini kurun.', points: ['Beyaz gürültü ve doğa sesleri', 'Uyku hikayeleri', 'Uyku zamanlayıcısı'] }],
    trust: { eyebrow: 'Yorgun ebeveynler için', title: 'Daha az uyku hesabı. Daha çok güven.', body: 'Yorix, her uykuyu, beslenmeyi veya bezi tabloya dönüştürmeden ailelere sakin bir yapı sağlar.', cards: [{ title: 'Daha az tahmin', body: 'Uyanıklık pencerelerini, uykuları ve sonraki iyi uyku anını anlamanın sakin yolu.' }, { title: 'Ortak hafıza', body: 'Her iki ebeveyn aynı uyku, beslenme, bez ve bakım verisini görebilir.' }, { title: 'Gerçek geceler için', body: 'Evde herkes yorgunken hızlı kayıt, yapay zeka desteği ve uyku sesleri.' }] },
    guides: { eyebrow: 'Yorix rehberleri', title: 'Uyku bilgisi güç verir.', body: 'Gece uyanmaları, uyanıklık pencereleri, uyku gerilemeleri, beslenme ve yaşa göre programlar için kanıta duyarlı rehberler.', action: 'Tüm rehberleri görüntüle', articles: englishGuideTitles.map((title) => ({ title, body: 'İngilizce ayrıntılı rehber.' })) },
    faq: { eyebrow: 'SSS', title: 'Bebek uykusu soruları, sakin cevaplarla.', items: [{ question: 'Yorix bir bebek uyku çizelgesinden nasıl farklıdır?', answer: 'Çizelgeler ortalamalar verir. Yorix, bir sonraki uyku penceresini uyarlamak için bebeğinizin gerçek uykularını, uyanıklık pencerelerini, gece uyanmalarını ve rutinini kullanır.' }, { question: 'Yorix’i yenidoğanla kullanabilir miyim?', answer: 'Evet. Yenidoğan döneminde Yorix; uyku, beslenme, bez ve bakım için basit bir kayıt olarak faydalıdır. Kalıplar oluştukça plan daha öngörücü olur.' }, { question: 'Yorix tıbbi önerinin yerini alır mı?', answer: 'Hayır. Yorix bir rutin yardımcısıdır, tıbbi hizmet değildir. Sağlık veya güvenlik endişelerinde uzman bir sağlık profesyoneline danışın.' }] },
    cta: { badge: 'Gerçek aile hayatı için', title: 'Bir uykuyla başlayın. Ritmi Yorix öğrensin.', body: 'Bugünün uykusunu, beslenmesini, bezlerini, büyümesini, belirtilerini ve rutinlerini takip edin; yarın için daha net bir plan alın.', action: 'Yorix’i indir' }, footer: 'Yorix ebeveynler için bir rutin yardımcısıdır. Tıbbi tanı veya acil öneri sunmaz.'
  },
  fr: {
    name: 'French', nativeName: 'Français', ogLocale: 'fr_FR',
    nav: { plan: 'Programme', features: 'Fonctionnalités', guides: 'Guides', faq: 'FAQ', download: "Télécharger l'app" },
    hero: { badge: 'Suivi du sommeil et planning IA pour bébé', title: 'Comprenez enfin le sommeil de votre bébé.', body: "Yorix apprend le rythme de votre enfant et transforme siestes, fenêtres d'éveil, repas, croissance et soins quotidiens en un programme qui s'adapte à la vraie vie de famille.", primary: 'Planifier la prochaine sieste', secondary: 'Lire les guides sommeil' },
    stats: ['langues', 'publicité dans votre routine', 'coach IA'],
    proof: [{ title: 'Planning de sommeil personnalisé', body: "La prochaine sieste et le coucher s'adaptent quand la journée change." }, { title: 'Coach sommeil IA 24/7', body: "Posez vos questions sur les fenêtres d'éveil, les courtes siestes et les routines." }, { title: 'Confidentiel par conception', body: 'Vos données vous appartiennent. Nous ne vendons pas vos données personnelles.' }],
    plan: { eyebrow: 'Votre bébé a un plan', title: 'Des signes de fatigue à une prochaine étape claire.', body: "Yorix répond à la question de chaque parent fatigué : quand mon bébé devrait-il dormir ensuite ? L'app suit le déroulement de la journée et garde le programme souple.", steps: ['Créer une routine adaptée à toute la famille', 'Prévenir la fatigue excessive avant le coucher', 'Apprendre des vrais rythmes de sommeil, repas et soins'] },
    stories: [{ eyebrow: 'Programme de journée intelligent', title: 'Sachez quand votre bébé devrait dormir ensuite.', body: "Yorix observe les siestes, les fenêtres d'éveil et le coucher, puis ajuste le programme quand la journée prend une autre tournure.", points: ["Fenêtres d'éveil adaptatives", 'Récupération après une courte sieste', 'Coucher qui suit la journée'] }, { eyebrow: 'Des progrès, pas des tableurs', title: 'Visualisez les rythmes de sommeil, repas, croissance et soins.', body: "Les données quotidiennes deviennent des tendances hebdomadaires claires. Suivez sommeil, allaitement, changes, promenades, bains, jeux, taille et poids sur une seule ligne du temps.", points: ['Tendances de sommeil et repas', 'Percentiles de croissance OMS', 'Historique de soins partagé'] }, { eyebrow: 'Coach sommeil IA', title: 'Posez la question que vous êtes trop fatigué pour chercher.', body: "Yorix aide avec les courtes siestes, réveils nocturnes, transitions, difficultés au coucher et questions de soins quotidiens.", points: ['École du sommeil', 'Facteurs de routine', "Programme d'aujourd'hui"] }, { eyebrow: 'Sons du coucher', title: 'Créez un environnement de sommeil familier.', body: 'Utilisez bruit blanc, rose ou brun, pluie, vagues, battements de cœur et histoires du soir avec une minuterie.', points: ['Bruit blanc et sons de nature', 'Histoires du coucher', 'Minuterie de sommeil'] }],
    trust: { eyebrow: 'Pour les parents fatigués', title: 'Moins de calculs. Plus de confiance.', body: "Yorix donne aux familles une structure apaisante sans transformer chaque sieste, repas ou change en tableur.", cards: [{ title: 'Moins de suppositions', body: "Une façon sereine de comprendre les fenêtres d'éveil, les siestes et le prochain bon moment pour dormir." }, { title: 'Une mémoire commune', body: 'Les deux parents voient les mêmes données de sommeil, repas, changes, croissance et soins.' }, { title: 'Pensé pour les vraies nuits', body: 'Saisie rapide, aide IA et sons du sommeil quand toute la maison est fatiguée.' }] },
    guides: { eyebrow: 'Guides Yorix', title: 'La connaissance du sommeil donne du pouvoir.', body: "Des guides attentifs aux données sur les réveils nocturnes, fenêtres d'éveil, régressions, repas et plannings selon l'âge.", action: 'Voir tous les guides', articles: englishGuideTitles.map((title) => ({ title, body: 'Guide détaillé disponible en anglais.' })) },
    faq: { eyebrow: 'FAQ', title: 'Les questions sur le sommeil, avec calme.', items: [{ question: "Qu'est-ce qui différencie Yorix d'un tableau de sommeil ?", answer: "Un tableau donne des moyennes. Yorix utilise les vraies siestes, fenêtres d'éveil, réveils, repas et l'historique de routine de votre bébé pour ajuster la prochaine fenêtre de sommeil." }, { question: 'Puis-je utiliser Yorix avec un nouveau-né ?', answer: "Oui. Au début, Yorix est un journal simple de sommeil, repas, changes et soins. Le programme devient plus prédictif à mesure que des tendances apparaissent." }, { question: 'Yorix remplace-t-il un avis médical ?', answer: "Non. Yorix aide à organiser la routine, ce n'est pas un service médical. Pour tout sujet de santé ou de sécurité, contactez un professionnel qualifié." }] },
    cta: { badge: 'Pensé pour la vraie vie de famille', title: 'Commencez avec une sieste. Laissez Yorix apprendre le rythme.', body: "Suivez le sommeil, les repas, les changes, la croissance, les symptômes et les routines d'aujourd'hui, puis obtenez un plan plus clair pour demain.", action: 'Télécharger Yorix' }, footer: "Yorix est une aide à la routine pour les parents. Il ne fournit ni diagnostic médical ni conseil d'urgence."
  },
  de: {
    name: 'German', nativeName: 'Deutsch', ogLocale: 'de_DE',
    nav: { plan: 'Plan', features: 'Funktionen', guides: 'Ratgeber', faq: 'FAQ', download: 'App herunterladen' },
    hero: { badge: 'Babyschlaf-Tracker und KI-Planer', title: 'Verstehen Sie endlich den Schlaf Ihres Babys.', body: 'Yorix lernt den Rhythmus Ihres Kindes und macht aus Nickerchen, Wachphasen, Mahlzeiten, Wachstum und täglicher Pflege einen Plan, der zum echten Familienalltag passt.', primary: 'Nächstes Nickerchen planen', secondary: 'Schlafratgeber lesen' },
    stats: ['Sprachen', 'Werbung in Ihrer Routine', 'KI-Coach'],
    proof: [{ title: 'Persönlicher Schlafplan', body: 'Das nächste Nickerchen und die Schlafenszeit passen sich an, wenn sich der Tag verändert.' }, { title: 'KI-Schlafcoach rund um die Uhr', body: 'Fragen Sie nach Wachphasen, kurzen Nickerchen und Routinen.' }, { title: 'Datenschutz von Anfang an', body: 'Ihre Daten gehören Ihnen. Wir verkaufen keine personenbezogenen Daten.' }],
    plan: { eyebrow: 'Ihr Baby hat einen Plan', title: 'Von Müdigkeitszeichen zum klaren nächsten Schritt.', body: 'Yorix konzentriert sich auf die Frage aller müden Eltern: Wann sollte mein Baby als Nächstes schlafen? Die App beobachtet den Tag und hält den Plan flexibel.', steps: ['Eine Routine für die ganze Familie aufbauen', 'Übermüdung vor dem Schlafengehen vermeiden', 'Aus echten Schlaf-, Ess- und Pflegemustern lernen'] },
    stories: [{ eyebrow: 'Intelligenter Tagesplan', title: 'Wissen, wann Ihr Baby als Nächstes schlafen sollte.', body: 'Yorix verfolgt Nickerchen, Wachphasen und Schlafenszeit und passt den Plan an, sobald der Tag anders verläuft.', points: ['Anpassbare Wachphasen', 'Erholung nach kurzen Nickerchen', 'Schlafenszeit, die sich mit dem Tag bewegt'] }, { eyebrow: 'Fortschritt statt Tabellen', title: 'Muster bei Schlaf, Ernährung, Wachstum und Pflege erkennen.', body: 'Tägliche Einträge werden zu klaren wöchentlichen Erkenntnissen. Verfolgen Sie Schlaf, Stillen, Windeln, Spaziergänge, Bad, Spiel, Größe und Gewicht in einer ruhigen Zeitleiste.', points: ['Schlaf- und Ernährungstrends', 'WHO-Wachstumsperzentile', 'Geteilte Pflegehistorie'] }, { eyebrow: 'KI-Schlafcoach', title: 'Stellen Sie die Frage, für deren Suche Sie zu müde sind.', body: 'Yorix hilft bei kurzen Nickerchen, nächtlichem Aufwachen, Übergängen, Schwierigkeiten beim Zubettgehen und Fragen zur täglichen Babypflege.', points: ['Schlafschule', 'Routinenfaktoren', 'Plan für heute'] }, { eyebrow: 'Klänge zum Einschlafen', title: 'Eine vertraute Schlafumgebung schaffen.', body: 'Nutzen Sie weißes, rosa oder braunes Rauschen, Regen, Meeresrauschen, Herzschlag und Gute-Nacht-Geschichten mit einem Schlaftimer.', points: ['Weißes Rauschen und Naturklänge', 'Gute-Nacht-Geschichten', 'Schlaftimer'] }],
    trust: { eyebrow: 'Für müde Eltern', title: 'Weniger Schlafrechnen. Mehr Sicherheit.', body: 'Yorix gibt Familien eine ruhige Struktur, ohne jedes Nickerchen, jede Mahlzeit oder Windel zur Tabelle zu machen.', cards: [{ title: 'Weniger Raten', body: 'Ein ruhiger Weg, Wachphasen, Nickerchen und den nächsten guten Schlafzeitpunkt zu verstehen.' }, { title: 'Gemeinsames Gedächtnis', body: 'Beide Eltern sehen dieselben Daten zu Schlaf, Ernährung, Windeln, Wachstum und Pflege.' }, { title: 'Für echte Nächte gemacht', body: 'Schnelle Einträge, KI-Hilfe und Schlafklänge, wenn das ganze Haus müde ist.' }] },
    guides: { eyebrow: 'Yorix Ratgeber', title: 'Schlafwissen gibt Kraft.', body: 'Evidenzbewusste Ratgeber zu nächtlichem Aufwachen, Wachphasen, Schlafregressionen, Ernährung und altersbezogenen Plänen.', action: 'Alle Ratgeber ansehen', articles: englishGuideTitles.map((title) => ({ title, body: 'Ausführlicher Ratgeber auf Englisch.' })) },
    faq: { eyebrow: 'FAQ', title: 'Babyschlaf-Fragen, ruhig beantwortet.', items: [{ question: 'Was unterscheidet Yorix von einer Babyschlaf-Tabelle?', answer: 'Eine Tabelle zeigt Durchschnittswerte. Yorix nutzt die echten Nickerchen, Wachphasen, nächtlichen Wachmomente, Mahlzeiten und die Routine Ihres Babys, um das nächste Schlaffenster anzupassen.' }, { question: 'Kann ich Yorix mit einem Neugeborenen nutzen?', answer: 'Ja. In der Neugeborenenzeit ist Yorix ein einfaches Protokoll für Schlaf, Ernährung, Windeln und Pflege. Mit entstehenden Mustern wird der Plan vorausschauender.' }, { question: 'Ersetzt Yorix medizinischen Rat?', answer: 'Nein. Yorix ist eine Hilfe für Routinen und kein medizinischer Dienst. Wenden Sie sich bei Gesundheits- oder Sicherheitsbedenken an qualifiziertes Fachpersonal.' }] },
    cta: { badge: 'Für den echten Familienalltag', title: 'Beginnen Sie mit einem Nickerchen. Yorix lernt den Rhythmus.', body: 'Verfolgen Sie Schlaf, Mahlzeiten, Windeln, Wachstum, Symptome und Routinen von heute und erhalten Sie einen klareren Plan für morgen.', action: 'Yorix herunterladen' }, footer: 'Yorix ist eine Routinehilfe für Eltern. Es bietet keine medizinische Diagnose oder Notfallberatung.'
  },
  ru: {
    name: 'Russian', nativeName: 'Русский', ogLocale: 'ru_RU',
    nav: { plan: 'План', features: 'Возможности', guides: 'Гайды', faq: 'Вопросы', download: 'Скачать приложение' },
    hero: { badge: 'Трекер сна малыша и планировщик с ИИ', title: 'Наконец поймите сон вашего малыша.', body: 'Yorix изучает ритм вашего ребенка и превращает дневные сны, окна бодрствования, кормления, рост и ежедневный уход в план, который адаптируется к реальной жизни семьи.', primary: 'Запланировать следующий сон', secondary: 'Читать гайды о сне' },
    stats: ['языков', 'рекламы в вашей рутине', 'ИИ-коуч'],
    proof: [{ title: 'Персональный план сна', body: 'Следующий сон и время отбоя адаптируются, когда день идет не по плану.' }, { title: 'ИИ-коуч по сну 24/7', body: 'Спрашивайте об окнах бодрствования, коротких снах и рутине.' }, { title: 'Приватность по умолчанию', body: 'Ваши данные принадлежат вам. Мы не продаем персональные данные.' }],
    plan: { eyebrow: 'У вашего малыша есть план', title: 'От признаков усталости к понятному следующему шагу.', body: 'Yorix отвечает на вопрос, который задает каждый уставший родитель: когда малышу пора спать дальше? Приложение следит за днем и сохраняет гибкость плана.', steps: ['Создайте рутину, которая подходит всей семье', 'Предотвращайте переутомление перед сном', 'Учитесь на реальных паттернах сна, кормлений и ухода'] },
    stories: [{ eyebrow: 'Умный план дня', title: 'Знайте, когда малышу пора спать дальше.', body: 'Yorix отслеживает дневные сны, окна бодрствования и отбой, а затем обновляет план, как только день меняется.', points: ['Адаптивные окна бодрствования', 'Восстановление после короткого сна', 'Отбой, который двигается вместе с днем'] }, { eyebrow: 'Прогресс, а не таблицы', title: 'Видьте закономерности сна, кормлений, роста и ухода.', body: 'Ежедневные записи превращаются в понятные недельные выводы. Отслеживайте сон, грудное вскармливание, подгузники, прогулки, купание, игры, рост и вес на одной спокойной шкале времени.', points: ['Тренды сна и кормлений', 'Перцентили роста ВОЗ', 'Общая история ухода'] }, { eyebrow: 'ИИ-коуч по сну', title: 'Задайте вопрос, который нет сил гуглить.', body: 'Yorix помогает с короткими снами, ночными пробуждениями, переходами между снами, сложным укладыванием и вопросами ежедневного ухода.', points: ['Школа сна', 'Факторы рутины', 'План на сегодня'] }, { eyebrow: 'Звуки для сна', title: 'Создайте привычную среду для сна.', body: 'Используйте белый, розовый и коричневый шум, дождь, океан, сердцебиение и сказки на ночь с простым таймером сна.', points: ['Белый шум и звуки природы', 'Сказки на ночь', 'Таймер сна'] }],
    trust: { eyebrow: 'Для уставших родителей', title: 'Меньше математики сна. Больше уверенности.', body: 'Yorix дает семье спокойную структуру, не превращая каждый сон, кормление или подгузник в электронную таблицу.', cards: [{ title: 'Меньше догадок', body: 'Спокойный способ понять окна бодрствования, дневные сны и следующий удачный момент для сна.' }, { title: 'Одна общая память', body: 'Оба родителя видят одни и те же данные о сне, кормлениях, подгузниках, росте и уходе.' }, { title: 'Создано для настоящих ночей', body: 'Быстрые записи, помощь ИИ и звуки для сна, когда устал весь дом.' }] },
    guides: { eyebrow: 'Гайды Yorix', title: 'Знания о сне дают силы.', body: 'Гайды с учетом доказательной базы о ночных пробуждениях, окнах бодрствования, регрессиях сна, кормлении и режимах по возрасту.', action: 'Все гайды', articles: englishGuideTitles.map((title) => ({ title, body: 'Подробный гайд пока доступен на английском.' })) },
    faq: { eyebrow: 'Вопросы', title: 'Вопросы о сне малыша, с ясными ответами.', items: [{ question: 'Чем Yorix отличается от таблицы сна?', answer: 'Таблица дает средние диапазоны. Yorix использует реальные сны, окна бодрствования, ночные пробуждения, кормления и историю рутины вашего малыша, чтобы адаптировать следующее окно сна.' }, { question: 'Можно ли использовать Yorix с новорожденным?', answer: 'Да. На этапе новорожденности Yorix полезен как простой журнал сна, кормлений, подгузников и ухода. По мере появления паттернов план становится более точным.' }, { question: 'Заменяет ли Yorix медицинскую консультацию?', answer: 'Нет. Yorix помогает с рутиной, но не является медицинским сервисом. При вопросах здоровья или безопасности обратитесь к квалифицированному врачу.' }] },
    cta: { badge: 'Для реальной жизни семьи', title: 'Начните с одного сна. Пусть Yorix изучит ритм.', body: 'Отслеживайте сегодняшний сон, кормления, подгузники, рост, симптомы и рутину, а затем получите более ясный план на следующий день.', action: 'Скачать Yorix' }, footer: 'Yorix — помощник с рутиной для родителей. Он не предоставляет медицинскую диагностику или экстренные рекомендации.'
  },
  nl: {
    name: 'Dutch', nativeName: 'Nederlands', ogLocale: 'nl_NL',
    nav: { plan: 'Plan', features: 'Functies', guides: 'Gidsen', faq: 'FAQ', download: 'Download de app' },
    hero: { badge: 'Babyslaaptracker en AI-planner', title: 'Begrijp eindelijk de slaap van je baby.', body: 'Yorix leert het ritme van je kind kennen en maakt van dutjes, wakkertijden, voeding, groei en dagelijkse zorg een plan dat zich aanpast aan het echte gezinsleven.', primary: 'Plan het volgende dutje', secondary: 'Lees slaapgidsen' },
    stats: ['talen', 'advertenties in je routine', 'AI-coach'],
    proof: [{ title: 'Persoonlijk slaapplan', body: 'Het volgende dutje en bedtijd passen zich aan wanneer de dag verandert.' }, { title: '24/7 AI-slaapcoach', body: 'Vraag naar wakkertijden, korte dutjes en routines.' }, { title: 'Privacy als uitgangspunt', body: 'Je gegevens zijn van jou. We verkopen geen persoonlijke gegevens.' }],
    plan: { eyebrow: 'Je baby heeft een plan', title: 'Van slaapsignalen naar een duidelijke volgende stap.', body: 'Yorix draait om de vraag van elke vermoeide ouder: wanneer moet mijn baby hierna slapen? De app volgt de dag en houdt het plan flexibel.', steps: ['Bouw een routine die voor iedereen werkt', 'Voorkom oververmoeidheid voor bedtijd', 'Leer van echte patronen in slaap, voeding en zorg'] },
    stories: [{ eyebrow: 'Slim dagplan', title: 'Weet wanneer je baby hierna moet slapen.', body: 'Yorix volgt dutjes, wakkertijden en bedtijd en past het plan aan zodra de dag anders loopt.', points: ['Flexibele wakkertijden', 'Herstel na korte dutjes', 'Bedtijd die meebeweegt met de dag'] }, { eyebrow: 'Voortgang, geen spreadsheets', title: 'Zie patronen in slaap, voeding, groei en zorg.', body: 'Dagelijkse logs worden heldere wekelijkse inzichten. Volg slaap, borstvoeding, luiers, wandelingen, bad, spel, lengte en gewicht in één rustige tijdlijn.', points: ['Slaap- en voedingstrends', 'WHO-groeipercentielen', 'Gedeelde zorggeschiedenis'] }, { eyebrow: 'AI-slaapcoach', title: 'Stel de vraag waarvoor je te moe bent om te googelen.', body: 'Yorix helpt met korte dutjes, nachtelijk wakker worden, slaapovergangen, bedtijdstrijd en dagelijkse zorgvragen.', points: ['Slaapschool', 'Routinefactoren', 'Plan van vandaag'] }, { eyebrow: 'Slaapgeluiden', title: 'Maak een vertrouwde slaapomgeving.', body: 'Gebruik witte, roze of bruine ruis, regen, oceaangeluiden, hartslag en verhaaltjes met een eenvoudige slaaptimer.', points: ['Witte ruis en natuurgeluiden', 'Bedtijdverhalen', 'Slaaptimer'] }],
    trust: { eyebrow: 'Voor vermoeide ouders', title: 'Minder slaaprekenen. Meer vertrouwen.', body: 'Yorix geeft gezinnen rustige structuur zonder elk dutje, elke voeding of luier in een spreadsheet te veranderen.', cards: [{ title: 'Minder gokken', body: 'Een rustige manier om wakkertijden, dutjes en het volgende goede slaapmoment te begrijpen.' }, { title: 'Eén gedeeld geheugen', body: 'Beide ouders zien dezelfde gegevens over slaap, voeding, luiers, groei en zorg.' }, { title: 'Gemaakt voor echte nachten', body: 'Snel loggen, AI-hulp en slaapgeluiden wanneer iedereen in huis moe is.' }] },
    guides: { eyebrow: 'Yorix-gidsen', title: 'Slaapkennis geeft kracht.', body: 'Praktische, evidence-aware gidsen over nachtelijk wakker worden, wakkertijden, slaapregressies, voeding en schema’s per leeftijd.', action: 'Bekijk alle gidsen', articles: englishGuideTitles.map((title) => ({ title, body: 'Uitgebreide gids beschikbaar in het Engels.' })) },
    faq: { eyebrow: 'FAQ', title: 'Vragen over babyslaap, rustig beantwoord.', items: [{ question: 'Wat maakt Yorix anders dan een babyslaapschema?', answer: 'Een schema geeft gemiddelden. Yorix gebruikt de echte dutjes, wakkertijden, nachtelijke ontwakingen, voedingen en routinegeschiedenis van je baby om het volgende slaapvenster aan te passen.' }, { question: 'Kan ik Yorix gebruiken met een pasgeborene?', answer: 'Ja. In de eerste fase is Yorix een eenvoudig logboek voor slaap, voeding, luiers en zorg. Wanneer patronen ontstaan, wordt het plan voorspellender.' }, { question: 'Vervangt Yorix medisch advies?', answer: 'Nee. Yorix is een routinehulp, geen medische dienst. Neem bij gezondheids- of veiligheidszorgen contact op met een gekwalificeerde zorgverlener.' }] },
    cta: { badge: 'Voor het echte gezinsleven', title: 'Begin met één dutje. Laat Yorix het ritme leren.', body: 'Volg slaap, voeding, luiers, groei, symptomen en routines van vandaag en krijg een duidelijker plan voor morgen.', action: 'Download Yorix' }, footer: 'Yorix is een routinehulp voor ouders. Het geeft geen medische diagnose of spoedadvies.'
  },
  it: {
    name: 'Italian', nativeName: 'Italiano', ogLocale: 'it_IT',
    nav: { plan: 'Piano', features: 'Funzioni', guides: 'Guide', faq: 'FAQ', download: "Scarica l'app" },
    hero: { badge: 'Tracker del sonno del neonato e programma IA', title: 'Finalmente capisci il sonno del tuo bambino.', body: "Yorix impara il ritmo del tuo bambino e trasforma pisolini, finestre di veglia, poppate, crescita e cura quotidiana in un programma che si adatta alla vita reale della famiglia.", primary: 'Pianifica il prossimo pisolino', secondary: 'Leggi le guide sul sonno' },
    stats: ['lingue', 'pubblicità nella tua routine', 'coach IA'],
    proof: [{ title: 'Programma del sonno personale', body: 'Il prossimo pisolino e l’orario della nanna si adattano quando la giornata cambia.' }, { title: 'Coach del sonno IA 24/7', body: 'Chiedi di finestre di veglia, pisolini brevi e routine.' }, { title: 'Privacy al centro', body: 'I tuoi dati sono tuoi. Non vendiamo dati personali.' }],
    plan: { eyebrow: 'Il tuo bambino ha un piano', title: 'Dai segnali di sonno al prossimo passo chiaro.', body: 'Yorix si concentra sulla domanda di ogni genitore stanco: quando dovrebbe dormire il mio bambino? L’app segue la giornata e mantiene il piano flessibile.', steps: ['Crea una routine che funzioni per tutti', 'Previeni la stanchezza eccessiva prima della nanna', 'Impara dai veri ritmi di sonno, poppate e cura'] },
    stories: [{ eyebrow: 'Piano giornaliero intelligente', title: 'Sapere quando il tuo bambino dovrebbe dormire.', body: 'Yorix segue pisolini, finestre di veglia e orario della nanna, poi aggiorna il piano quando la giornata cambia.', points: ['Finestre di veglia adattive', 'Recupero dopo pisolini brevi', 'Nanna che segue la giornata'] }, { eyebrow: 'Progressi, non fogli di calcolo', title: 'Vedi schemi di sonno, alimentazione, crescita e cura.', body: 'I registri quotidiani diventano informazioni settimanali chiare. Segui sonno, allattamento, pannolini, passeggiate, bagnetto, gioco, altezza e peso in un’unica cronologia.', points: ['Tendenze di sonno e poppate', 'Percentili di crescita OMS', 'Cronologia di cura condivisa'] }, { eyebrow: 'Coach del sonno IA', title: 'Fai la domanda che sei troppo stanco per cercare.', body: 'Yorix aiuta con pisolini brevi, risvegli notturni, transizioni, difficoltà al momento della nanna e domande sulla cura quotidiana.', points: ['Scuola del sonno', 'Fattori della routine', 'Piano di oggi'] }, { eyebrow: 'Suoni per la nanna', title: 'Crea un ambiente di sonno familiare.', body: 'Usa rumore bianco, rosa o marrone, pioggia, onde dell’oceano, battito cardiaco e storie della buonanotte con un semplice timer.', points: ['Rumore bianco e suoni naturali', 'Storie della buonanotte', 'Timer del sonno'] }],
    trust: { eyebrow: 'Per genitori stanchi', title: 'Meno calcoli sul sonno. Più fiducia.', body: 'Yorix offre alle famiglie una struttura serena senza trasformare ogni pisolino, poppata o pannolino in un foglio di calcolo.', cards: [{ title: 'Meno tentativi', body: 'Un modo calmo per capire finestre di veglia, pisolini e il prossimo buon momento per dormire.' }, { title: 'Una memoria condivisa', body: 'Entrambi i genitori vedono gli stessi dati su sonno, poppate, pannolini, crescita e cura.' }, { title: 'Pensato per le notti vere', body: 'Registrazione rapida, aiuto IA e suoni del sonno quando tutta la casa è stanca.' }] },
    guides: { eyebrow: 'Guide Yorix', title: 'La conoscenza del sonno dà forza.', body: 'Guide attente alle evidenze su risvegli notturni, finestre di veglia, regressioni, poppate e programmi per età.', action: 'Vedi tutte le guide', articles: englishGuideTitles.map((title) => ({ title, body: 'Guida dettagliata disponibile in inglese.' })) },
    faq: { eyebrow: 'FAQ', title: 'Domande sul sonno del bambino, risposte con calma.', items: [{ question: 'Cosa rende Yorix diverso da una tabella del sonno?', answer: 'Una tabella offre intervalli medi. Yorix usa i veri pisolini, finestre di veglia, risvegli notturni, poppate e cronologia della routine del tuo bambino per adattare la prossima finestra di sonno.' }, { question: 'Posso usare Yorix con un neonato?', answer: 'Sì. Nella fase neonatale Yorix è utile come registro semplice di sonno, poppate, pannolini e cura. Il piano diventa più predittivo con l’emergere dei ritmi.' }, { question: 'Yorix sostituisce il parere medico?', answer: 'No. Yorix è un aiuto per la routine, non un servizio medico. Per dubbi di salute o sicurezza, contatta un professionista qualificato.' }] },
    cta: { badge: 'Per la vita vera in famiglia', title: 'Inizia con un pisolino. Lascia che Yorix impari il ritmo.', body: 'Segui il sonno, le poppate, i pannolini, la crescita, i sintomi e le routine di oggi, poi ottieni un piano più chiaro per domani.', action: 'Scarica Yorix' }, footer: 'Yorix è un aiuto alla routine per genitori. Non fornisce diagnosi mediche o consigli di emergenza.'
  },
  pt: {
    name: 'Portuguese', nativeName: 'Português', ogLocale: 'pt_PT',
    nav: { plan: 'Plano', features: 'Funcionalidades', guides: 'Guias', faq: 'FAQ', download: 'Transferir a aplicação' },
    hero: { badge: 'Monitor de sono do bebé e plano com IA', title: 'Finalmente compreenda o sono do seu bebé.', body: 'O Yorix aprende o ritmo da criança e transforma sestas, janelas de vigília, alimentação, crescimento e cuidados diários num plano que se adapta à vida real da família.', primary: 'Planear a próxima sesta', secondary: 'Ler guias de sono' },
    stats: ['idiomas', 'anúncios na sua rotina', 'coach de IA'],
    proof: [{ title: 'Plano de sono personalizado', body: 'A próxima sesta e a hora de deitar adaptam-se quando o dia muda.' }, { title: 'Coach de sono com IA 24/7', body: 'Pergunte sobre janelas de vigília, sestas curtas e rotinas.' }, { title: 'Privacidade por defeito', body: 'Os seus dados pertencem-lhe. Não vendemos dados pessoais.' }],
    plan: { eyebrow: 'O seu bebé tem um plano', title: 'Dos sinais de sono ao próximo passo claro.', body: 'O Yorix foi criado em torno da pergunta de cada pai cansado: quando deve o meu bebé dormir a seguir? A aplicação acompanha o dia e mantém o plano flexível.', steps: ['Criar uma rotina que funciona para todos', 'Evitar cansaço excessivo antes de deitar', 'Aprender com padrões reais de sono, alimentação e cuidados'] },
    stories: [{ eyebrow: 'Plano diário inteligente', title: 'Saiba quando o bebé deve dormir a seguir.', body: 'O Yorix acompanha sestas, janelas de vigília e hora de deitar, depois atualiza o plano quando o dia muda.', points: ['Janelas de vigília adaptáveis', 'Recuperação após sestas curtas', 'Hora de deitar que acompanha o dia'] }, { eyebrow: 'Progresso, não folhas de cálculo', title: 'Veja padrões de sono, alimentação, crescimento e cuidados.', body: 'Registos diários tornam-se informações semanais claras. Acompanhe sono, amamentação, fraldas, passeios, banho, brincadeira, altura e peso numa só cronologia.', points: ['Tendências de sono e alimentação', 'Percentis de crescimento da OMS', 'Histórico de cuidados partilhado'] }, { eyebrow: 'Coach de sono com IA', title: 'Faça a pergunta que está demasiado cansado para pesquisar.', body: 'O Yorix ajuda com sestas curtas, despertares noturnos, transições, dificuldades ao deitar e questões de cuidados diários.', points: ['Escola do sono', 'Fatores da rotina', 'Plano de hoje'] }, { eyebrow: 'Sons para dormir', title: 'Crie um ambiente de sono familiar.', body: 'Use ruído branco, rosa ou castanho, chuva, ondas do mar, batimento cardíaco e histórias de embalar com um temporizador simples.', points: ['Ruído branco e sons da natureza', 'Histórias de embalar', 'Temporizador de sono'] }],
    trust: { eyebrow: 'Para pais cansados', title: 'Menos contas do sono. Mais confiança.', body: 'O Yorix oferece às famílias uma estrutura tranquila sem transformar cada sesta, alimentação ou fralda numa folha de cálculo.', cards: [{ title: 'Menos adivinhação', body: 'Uma forma calma de compreender janelas de vigília, sestas e o próximo bom momento de sono.' }, { title: 'Uma memória partilhada', body: 'Ambos os pais veem os mesmos dados de sono, alimentação, fraldas, crescimento e cuidados.' }, { title: 'Feito para noites reais', body: 'Registo rápido, ajuda de IA e sons de sono quando toda a casa está cansada.' }] },
    guides: { eyebrow: 'Guias Yorix', title: 'Conhecimento sobre sono dá força.', body: 'Guias atentos à evidência sobre despertares noturnos, janelas de vigília, regressões, alimentação e planos por idade.', action: 'Ver todos os guias', articles: englishGuideTitles.map((title) => ({ title, body: 'Guia detalhado disponível em inglês.' })) },
    faq: { eyebrow: 'FAQ', title: 'Perguntas sobre sono do bebé, respondidas com calma.', items: [{ question: 'O que torna o Yorix diferente de uma tabela de sono?', answer: 'Uma tabela dá intervalos médios. O Yorix usa as sestas reais, janelas de vigília, despertares noturnos, refeições e o histórico de rotina do bebé para adaptar a próxima janela de sono.' }, { question: 'Posso usar o Yorix com um recém-nascido?', answer: 'Sim. Na fase de recém-nascido, o Yorix é útil como registo simples de sono, alimentação, fraldas e cuidados. O plano torna-se mais preditivo quando surgem padrões.' }, { question: 'O Yorix substitui aconselhamento médico?', answer: 'Não. O Yorix é um apoio à rotina, não um serviço médico. Para dúvidas de saúde ou segurança, contacte um profissional qualificado.' }] },
    cta: { badge: 'Para a vida real em família', title: 'Comece com uma sesta. Deixe o Yorix aprender o ritmo.', body: 'Acompanhe o sono, refeições, fraldas, crescimento, sintomas e rotinas de hoje e obtenha um plano mais claro para amanhã.', action: 'Transferir Yorix' }, footer: 'O Yorix é um apoio à rotina para pais. Não fornece diagnóstico médico nem aconselhamento de emergência.'
  },
  es: {
    name: 'Spanish', nativeName: 'Español', ogLocale: 'es_ES',
    nav: { plan: 'Plan', features: 'Funciones', guides: 'Guías', faq: 'Preguntas', download: 'Descargar la app' },
    hero: { badge: 'Monitor de sueño del bebé y planificador con IA', title: 'Por fin entiende el sueño de tu bebé.', body: 'Yorix aprende el ritmo de tu hijo y convierte siestas, ventanas de vigilia, alimentación, crecimiento y cuidados diarios en un plan que se adapta a la vida real de la familia.', primary: 'Planificar la próxima siesta', secondary: 'Leer guías de sueño' },
    stats: ['idiomas', 'anuncios en tu rutina', 'coach de IA'],
    proof: [{ title: 'Plan de sueño personalizado', body: 'La siguiente siesta y la hora de dormir se adaptan cuando el día cambia.' }, { title: 'Coach de sueño con IA 24/7', body: 'Pregunta sobre ventanas de vigilia, siestas cortas y rutinas.' }, { title: 'Privacidad desde el diseño', body: 'Tus datos son tuyos. No vendemos datos personales.' }],
    plan: { eyebrow: 'Tu bebé tiene un plan', title: 'De las señales de sueño al siguiente paso claro.', body: 'Yorix se centra en la pregunta de cada madre y padre cansado: ¿cuándo debería dormir mi bebé después? La app sigue el día y mantiene el plan flexible.', steps: ['Crea una rutina que funcione para todos', 'Evita el cansancio excesivo antes de dormir', 'Aprende de patrones reales de sueño, alimentación y cuidados'] },
    stories: [{ eyebrow: 'Plan diario inteligente', title: 'Sabe cuándo debería dormir tu bebé después.', body: 'Yorix sigue siestas, ventanas de vigilia y hora de dormir, y actualiza el plan cuando el día cambia.', points: ['Ventanas de vigilia adaptativas', 'Recuperación tras siestas cortas', 'Hora de dormir que se mueve con el día'] }, { eyebrow: 'Progreso, no hojas de cálculo', title: 'Ve patrones de sueño, alimentación, crecimiento y cuidados.', body: 'Los registros diarios se convierten en información semanal clara. Sigue sueño, lactancia, pañales, paseos, baño, juego, altura y peso en una sola línea de tiempo.', points: ['Tendencias de sueño y alimentación', 'Percentiles de crecimiento de la OMS', 'Historial de cuidados compartido'] }, { eyebrow: 'Coach de sueño con IA', title: 'Haz la pregunta que estás demasiado cansado para buscar.', body: 'Yorix ayuda con siestas cortas, despertares nocturnos, transiciones, dificultades a la hora de dormir y dudas sobre los cuidados diarios.', points: ['Escuela del sueño', 'Factores de la rutina', 'Plan de hoy'] }, { eyebrow: 'Sonidos para dormir', title: 'Crea un entorno de sueño familiar.', body: 'Usa ruido blanco, rosa o marrón, lluvia, olas del mar, latidos e historias para dormir con un temporizador sencillo.', points: ['Ruido blanco y sonidos naturales', 'Historias para dormir', 'Temporizador de sueño'] }],
    trust: { eyebrow: 'Para padres cansados', title: 'Menos cálculos de sueño. Más confianza.', body: 'Yorix da a las familias una estructura tranquila sin convertir cada siesta, toma o pañal en una hoja de cálculo.', cards: [{ title: 'Menos conjeturas', body: 'Una manera tranquila de entender ventanas de vigilia, siestas y el próximo buen momento para dormir.' }, { title: 'Una memoria compartida', body: 'Ambos progenitores ven los mismos datos de sueño, alimentación, pañales, crecimiento y cuidados.' }, { title: 'Hecho para noches reales', body: 'Registro rápido, ayuda de IA y sonidos de sueño cuando toda la casa está cansada.' }] },
    guides: { eyebrow: 'Guías Yorix', title: 'El conocimiento sobre el sueño da fuerza.', body: 'Guías basadas en evidencia sobre despertares nocturnos, ventanas de vigilia, regresiones, alimentación y horarios por edad.', action: 'Ver todas las guías', articles: englishGuideTitles.map((title) => ({ title, body: 'Guía detallada disponible en inglés.' })) },
    faq: { eyebrow: 'Preguntas frecuentes', title: 'Preguntas sobre el sueño del bebé, respondidas con calma.', items: [{ question: '¿Qué hace diferente a Yorix de una tabla de sueño?', answer: 'Una tabla ofrece rangos medios. Yorix usa las siestas reales, ventanas de vigilia, despertares nocturnos, tomas e historial de rutina de tu bebé para ajustar la siguiente ventana de sueño.' }, { question: '¿Puedo usar Yorix con un recién nacido?', answer: 'Sí. En la etapa de recién nacido, Yorix es útil como registro sencillo de sueño, alimentación, pañales y cuidados. El plan se vuelve más predictivo cuando aparecen patrones.' }, { question: '¿Yorix sustituye el consejo médico?', answer: 'No. Yorix es una ayuda para la rutina, no un servicio médico. Para dudas de salud o seguridad, consulta a un profesional cualificado.' }] },
    cta: { badge: 'Para la vida familiar real', title: 'Empieza con una siesta. Deja que Yorix aprenda el ritmo.', body: 'Sigue el sueño, las tomas, los pañales, el crecimiento, los síntomas y las rutinas de hoy, y consigue un plan más claro para mañana.', action: 'Descargar Yorix' }, footer: 'Yorix es una ayuda de rutina para madres y padres. No proporciona diagnósticos médicos ni consejos de emergencia.'
  }
} as Record<Locale, LocaleCopy>;

type CompactLocaleInput = Pick<LocaleCopy, 'name' | 'nativeName' | 'ogLocale' | 'nav' | 'hero' | 'stats' | 'proof' | 'plan' | 'trust' | 'faq' | 'cta' | 'footer'> & {
  stories: [string, string, string, string];
  storyBodies: [string, string, string, string];
  sleepSounds: string;
  guideBody: string;
  guideAction: string;
};

function compactLocale(input: CompactLocaleInput): LocaleCopy {
  const labels = [input.nav.plan, input.nav.features, 'AI', input.sleepSounds];
  return {
    ...input,
    stories: input.stories.map((title, index) => ({
      eyebrow: labels[index],
      title,
      body: input.storyBodies[index],
      points: index === 3 ? [input.sleepSounds, input.plan.steps[0], input.plan.steps[1]] : input.plan.steps,
    })) as LocaleCopy['stories'],
    guides: {
      eyebrow: 'Yorix guides',
      title: input.nav.guides,
      body: input.guideBody,
      action: input.guideAction,
      articles: englishGuideTitles.map((title) => ({ title, body: input.guideBody })),
    },
  };
}

Object.assign(localeCopy, {
  th: compactLocale({
    name: 'Thai', nativeName: 'ไทย', ogLocale: 'th_TH', nav: { plan: 'แผน', features: 'ฟีเจอร์', guides: 'คู่มือ', faq: 'คำถาม', download: 'ดาวน์โหลดแอป' },
    hero: { badge: 'ตัวติดตามการนอนของทารกและตาราง AI', title: 'เข้าใจการนอนของลูกน้อยได้อย่างแท้จริง', body: 'Yorix เรียนรู้จังหวะของลูกและเปลี่ยนงีบ ช่วงเวลาตื่น การกิน การเติบโต และการดูแลประจำวันให้เป็นแผนที่ยืดหยุ่นตามชีวิตครอบครัวจริง', primary: 'วางแผนการงีบครั้งถัดไป', secondary: 'อ่านคู่มือการนอน' }, stats: ['ภาษา', 'โฆษณาในกิจวัตร', 'โค้ช AI'],
    proof: [{ title: 'แผนการนอนเฉพาะบุคคล', body: 'เวลางีบและเวลาเข้านอนถัดไปปรับตามวันที่เปลี่ยนไป' }, { title: 'โค้ชการนอน AI ตลอด 24 ชั่วโมง', body: 'ถามเรื่องช่วงเวลาตื่น งีบสั้น และกิจวัตรได้ทุกเมื่อ' }, { title: 'ออกแบบโดยคำนึงถึงความเป็นส่วนตัว', body: 'ข้อมูลเป็นของคุณ เราไม่ขายข้อมูลส่วนบุคคล' }],
    plan: { eyebrow: 'ลูกน้อยมีแผนของตัวเอง', title: 'จากสัญญาณง่วงสู่ขั้นตอนถัดไปที่ชัดเจน', body: 'Yorix ตอบคำถามของผู้ปกครองที่เหนื่อยล้า: ลูกควรนอนครั้งต่อไปเมื่อไร แอปติดตามวันของคุณและทำให้แผนยืดหยุ่นเสมอ', steps: ['สร้างกิจวัตรที่เหมาะกับทุกคน', 'ป้องกันความเหนื่อยเกินก่อนนอน', 'เรียนรู้จากรูปแบบการนอนและการดูแลจริง'] },
    stories: ['รู้เวลานอนครั้งถัดไปของลูก', 'เห็นรูปแบบการนอนและการเติบโต', 'ถามคำถามที่ไม่มีแรงค้นหา', 'สร้างบรรยากาศนอนที่คุ้นเคย'], storyBodies: ['Yorix ปรับแผนทันทีเมื่อวันไม่เป็นไปตามคาด', 'บันทึกประจำวันกลายเป็นข้อมูลเชิงลึกที่เข้าใจง่าย', 'รับคำแนะนำเรื่องงีบสั้น ตื่นกลางคืน และเวลาเข้านอน', 'ใช้เสียงผ่อนคลายเพื่อสนับสนุนกิจวัตรก่อนนอน'], sleepSounds: 'เสียงขาวและเสียงธรรมชาติ',
    trust: { eyebrow: 'สำหรับผู้ปกครองที่เหนื่อยล้า', title: 'คำนวณเรื่องการนอนน้อยลง มั่นใจมากขึ้น', body: 'Yorix ช่วยให้ครอบครัวมีโครงสร้างที่สงบโดยไม่ทำให้ทุกการงีบหรือมื้ออาหารกลายเป็นตาราง', cards: [{ title: 'เดาน้อยลง', body: 'เข้าใจช่วงเวลาตื่นและเวลานอนที่เหมาะสมได้ง่ายขึ้น' }, { title: 'ความทรงจำร่วมกัน', body: 'ผู้ปกครองทั้งสองเห็นข้อมูลการดูแลเดียวกัน' }, { title: 'สำหรับคืนจริง', body: 'บันทึกเร็ว ความช่วยเหลือ AI และเสียงสำหรับนอน' }] },
    faq: { eyebrow: 'คำถามที่พบบ่อย', title: 'คำถามเรื่องการนอนของทารก ตอบอย่างใจเย็น', items: [{ question: 'Yorix ต่างจากตารางการนอนอย่างไร', answer: 'ตารางให้ค่าเฉลี่ย แต่ Yorix ใช้การนอนและกิจวัตรจริงของลูกเพื่อปรับช่วงเวลานอนถัดไป' }, { question: 'ใช้ Yorix กับทารกแรกเกิดได้ไหม', answer: 'ได้ Yorix เป็นบันทึกง่าย ๆ สำหรับการนอน การกิน ผ้าอ้อม และการดูแลตั้งแต่แรกเริ่ม' }, { question: 'Yorix แทนคำแนะนำทางการแพทย์หรือไม่', answer: 'ไม่ Yorix เป็นผู้ช่วยด้านกิจวัตร โปรดปรึกษาผู้เชี่ยวชาญเมื่อมีข้อกังวลด้านสุขภาพ' }] },
    cta: { badge: 'สร้างเพื่อชีวิตครอบครัวจริง', title: 'เริ่มด้วยการงีบหนึ่งครั้ง ให้ Yorix เรียนรู้จังหวะ', body: 'ติดตามการนอน การกิน ผ้าอ้อม การเติบโต และกิจวัตรของวันนี้ เพื่อแผนที่ชัดเจนขึ้นสำหรับวันพรุ่งนี้', action: 'ดาวน์โหลด Yorix' }, footer: 'Yorix เป็นผู้ช่วยด้านกิจวัตรสำหรับผู้ปกครอง ไม่ใช่การวินิจฉัยหรือคำแนะนำทางการแพทย์ฉุกเฉิน', guideBody: 'คู่มือฉบับละเอียดมีให้บริการเป็นภาษาอังกฤษ', guideAction: 'ดูคู่มือทั้งหมด'
  }),
  sv: compactLocale({
    name: 'Swedish', nativeName: 'Svenska', ogLocale: 'sv_SE', nav: { plan: 'Plan', features: 'Funktioner', guides: 'Guider', faq: 'FAQ', download: 'Hämta appen' },
    hero: { badge: 'Sömnspårare och AI-plan för bebisar', title: 'Förstå äntligen ditt barns sömn.', body: 'Yorix lär sig ditt barns rytm och gör tupplurar, vakentider, matning, tillväxt och vardagsomsorg till en plan som anpassas till familjens verkliga liv.', primary: 'Planera nästa tupplur', secondary: 'Läs sömnguider' }, stats: ['språk', 'annonser i din rutin', 'AI-coach'],
    proof: [{ title: 'Personlig sömnplan', body: 'Nästa tupplur och läggdags anpassas när dagen förändras.' }, { title: 'AI-sömncoach dygnet runt', body: 'Fråga om vakentider, korta tupplurar och rutiner.' }, { title: 'Integritet från början', body: 'Din data är din. Vi säljer inte personuppgifter.' }],
    plan: { eyebrow: 'Din bebis har en plan', title: 'Från trötthetssignaler till nästa tydliga steg.', body: 'Yorix fokuserar på frågan varje trött förälder ställer: när ska min bebis sova nästa gång? Appen följer dagen och håller planen flexibel.', steps: ['Bygg en rutin som fungerar för alla', 'Förebygg övertrötthet före läggdags', 'Lär av verkliga mönster för sömn och omsorg'] },
    stories: ['Vet när barnet bör sova nästa gång', 'Se mönster i sömn och tillväxt', 'Fråga när du är för trött för att söka', 'Skapa en välbekant sovmiljö'], storyBodies: ['Yorix justerar planen när dagen ändras', 'Dagliga loggar blir tydliga veckovisa insikter', 'Få hjälp med korta tupplurar och nattliga uppvaknanden', 'Lugnande ljud stödjer kvällsrutinen'], sleepSounds: 'Vitt brus och naturljud',
    trust: { eyebrow: 'För trötta föräldrar', title: 'Mindre sömnmatte. Mer trygghet.', body: 'Yorix ger familjer lugn struktur utan att göra varje tupplur eller blöja till ett kalkylblad.', cards: [{ title: 'Mindre gissande', body: 'Förstå vakentider och nästa bra sovstund.' }, { title: 'Ett delat minne', body: 'Båda föräldrarna ser samma omsorgsdata.' }, { title: 'Gjord för riktiga nätter', body: 'Snabb loggning, AI-hjälp och sovljud.' }] },
    faq: { eyebrow: 'FAQ', title: 'Frågor om bebissömn, lugnt besvarade.', items: [{ question: 'Hur skiljer sig Yorix från ett sömnschema?', answer: 'Ett schema visar genomsnitt. Yorix använder ditt barns verkliga sömn och rutin för att anpassa nästa sömnfönster.' }, { question: 'Kan jag använda Yorix med en nyfödd?', answer: 'Ja. Yorix är en enkel logg för sömn, matning, blöjor och omsorg från början.' }, { question: 'Ersätter Yorix medicinsk rådgivning?', answer: 'Nej. Yorix är en rutinhjälp. Kontakta kvalificerad vårdpersonal vid hälsofrågor.' }] },
    cta: { badge: 'För verkligt familjeliv', title: 'Börja med en tupplur. Låt Yorix lära sig rytmen.', body: 'Följ dagens sömn, matning, blöjor, tillväxt och rutiner och få en tydligare plan för morgondagen.', action: 'Hämta Yorix' }, footer: 'Yorix är en rutinhjälp för föräldrar och ger inte medicinsk diagnos eller akutråd.', guideBody: 'Detaljerade guider finns på engelska.', guideAction: 'Se alla guider'
  }),
  id: compactLocale({
    name: 'Indonesian', nativeName: 'Bahasa Indonesia', ogLocale: 'id_ID', nav: { plan: 'Rencana', features: 'Fitur', guides: 'Panduan', faq: 'FAQ', download: 'Unduh aplikasi' },
    hero: { badge: 'Pelacak tidur bayi dan jadwal AI', title: 'Akhirnya pahami tidur bayi Anda.', body: 'Yorix mempelajari ritme anak Anda dan mengubah tidur siang, jendela bangun, makan, tumbuh kembang, serta perawatan harian menjadi rencana yang menyesuaikan kehidupan keluarga nyata.', primary: 'Rencanakan tidur berikutnya', secondary: 'Baca panduan tidur' }, stats: ['bahasa', 'iklan dalam rutinitas', 'pelatih AI'],
    proof: [{ title: 'Jadwal tidur personal', body: 'Tidur berikutnya dan waktu tidur malam menyesuaikan saat hari berubah.' }, { title: 'Pelatih tidur AI 24/7', body: 'Tanyakan tentang jendela bangun, tidur singkat, dan rutinitas.' }, { title: 'Privasi sejak awal', body: 'Data Anda milik Anda. Kami tidak menjual data pribadi.' }],
    plan: { eyebrow: 'Bayi Anda punya rencana', title: 'Dari tanda mengantuk ke langkah berikutnya yang jelas.', body: 'Yorix menjawab pertanyaan setiap orang tua yang lelah: kapan bayi saya harus tidur lagi? Aplikasi mengikuti hari dan membuat rencana tetap fleksibel.', steps: ['Buat rutinitas yang cocok untuk semua', 'Cegah kelelahan berlebih sebelum tidur', 'Belajar dari pola tidur dan perawatan nyata'] },
    stories: ['Tahu kapan bayi perlu tidur lagi', 'Lihat pola tidur dan pertumbuhan', 'Tanyakan saat terlalu lelah untuk mencari', 'Ciptakan suasana tidur yang akrab'], storyBodies: ['Yorix menyesuaikan rencana saat hari berubah', 'Catatan harian menjadi wawasan mingguan yang jelas', 'Dapatkan bantuan untuk tidur singkat dan terbangun malam hari', 'Suara menenangkan mendukung rutinitas malam'], sleepSounds: 'White noise dan suara alam',
    trust: { eyebrow: 'Untuk orang tua lelah', title: 'Lebih sedikit hitung tidur. Lebih percaya diri.', body: 'Yorix memberi keluarga struktur yang tenang tanpa mengubah setiap tidur, makan, atau popok menjadi spreadsheet.', cards: [{ title: 'Lebih sedikit menebak', body: 'Pahami jendela bangun dan waktu tidur berikutnya.' }, { title: 'Satu memori bersama', body: 'Kedua orang tua melihat data perawatan yang sama.' }, { title: 'Untuk malam yang nyata', body: 'Pencatatan cepat, bantuan AI, dan suara tidur.' }] },
    faq: { eyebrow: 'FAQ', title: 'Pertanyaan tidur bayi, dijawab dengan tenang.', items: [{ question: 'Apa bedanya Yorix dengan tabel tidur?', answer: 'Tabel memberi rata-rata. Yorix memakai tidur dan rutinitas nyata bayi untuk menyesuaikan jendela tidur berikutnya.' }, { question: 'Bisakah menggunakan Yorix untuk bayi baru lahir?', answer: 'Ya. Yorix adalah catatan sederhana untuk tidur, makan, popok, dan perawatan sejak awal.' }, { question: 'Apakah Yorix menggantikan saran medis?', answer: 'Tidak. Yorix adalah bantuan rutinitas. Hubungi tenaga kesehatan untuk kekhawatiran kesehatan.' }] },
    cta: { badge: 'Untuk kehidupan keluarga nyata', title: 'Mulai dari satu tidur. Biarkan Yorix mempelajari ritmenya.', body: 'Lacak tidur, makan, popok, pertumbuhan, dan rutinitas hari ini untuk rencana yang lebih jelas besok.', action: 'Unduh Yorix' }, footer: 'Yorix adalah bantuan rutinitas untuk orang tua dan bukan diagnosis atau saran medis darurat.', guideBody: 'Panduan terperinci tersedia dalam bahasa Inggris.', guideAction: 'Lihat semua panduan'
  }),
  ja: compactLocale({
    name: 'Japanese', nativeName: '日本語', ogLocale: 'ja_JP', nav: { plan: 'プラン', features: '機能', guides: 'ガイド', faq: 'よくある質問', download: 'アプリをダウンロード' },
    hero: { badge: '赤ちゃんの睡眠トラッカーとAIスケジュール', title: '赤ちゃんの睡眠を、ようやく理解できる。', body: 'Yorixはお子さまのリズムを学び、昼寝、起きている時間、授乳、成長、毎日のお世話を、実際の家族の暮らしに合わせて変化するプランにします。', primary: '次の昼寝を計画する', secondary: '睡眠ガイドを読む' }, stats: ['言語', 'ルーティン内の広告', 'AIコーチ'],
    proof: [{ title: 'パーソナル睡眠プラン', body: '一日の変化に合わせて、次の昼寝と就寝時間が調整されます。' }, { title: '24時間AI睡眠コーチ', body: '起きている時間、短い昼寝、ルーティンについて質問できます。' }, { title: 'プライバシーを大切に', body: 'データはあなたのものです。個人データを販売しません。' }],
    plan: { eyebrow: '赤ちゃんにはプランがあります', title: '眠そうなサインから、わかりやすい次の一歩へ。', body: 'Yorixは、疲れた親がいつも抱く「次はいつ寝るべき？」という問いに寄り添います。アプリは一日の流れを見守り、プランを柔軟に保ちます。', steps: ['家族みんなに合うルーティンをつくる', '就寝前の疲れすぎを防ぐ', '実際の睡眠とお世話のパターンから学ぶ'] },
    stories: ['次に眠る時間がわかる', '睡眠と成長のパターンを見る', '検索する元気がないときに質問する', '慣れ親しんだ睡眠環境をつくる'], storyBodies: ['一日の変化に合わせてYorixがプランを調整します', '毎日の記録が、わかりやすい週ごとの気づきになります', '短い昼寝や夜の目覚めについてサポートします', '落ち着く音が就寝前のルーティンを支えます'], sleepSounds: 'ホワイトノイズと自然音',
    trust: { eyebrow: '疲れた親のために', title: '睡眠の計算を減らして、安心を増やす。', body: 'Yorixは、昼寝や授乳、おむつ替えのたびに表計算を作ることなく、家族に穏やかな見通しを与えます。', cards: [{ title: '迷いを減らす', body: '起きている時間と次のよい睡眠のタイミングを理解できます。' }, { title: '共有の記憶', body: '両親が同じお世話のデータを確認できます。' }, { title: '現実の夜のために', body: 'すばやい記録、AIの助け、睡眠の音。' }] },
    faq: { eyebrow: 'よくある質問', title: '赤ちゃんの睡眠の疑問に、穏やかに答えます。', items: [{ question: 'Yorixは睡眠表と何が違いますか？', answer: '睡眠表は平均値を示します。Yorixは赤ちゃんの実際の睡眠とルーティンから、次の睡眠時間を調整します。' }, { question: '新生児にもYorixを使えますか？', answer: 'はい。最初から睡眠、授乳、おむつ、お世話のシンプルな記録として使えます。' }, { question: 'Yorixは医療アドバイスの代わりになりますか？', answer: 'いいえ。Yorixはルーティンのサポートです。健康上の心配は医療専門家にご相談ください。' }] },
    cta: { badge: '実際の家族の暮らしのために', title: 'まず一度の昼寝から。Yorixにリズムを学ばせましょう。', body: '今日の睡眠、授乳、おむつ、成長、ルーティンを記録して、明日のより明確なプランを手に入れましょう。', action: 'Yorixをダウンロード' }, footer: 'Yorixは親のためのルーティン支援です。医療診断や緊急の助言は提供しません。', guideBody: '詳細なガイドは英語でご利用いただけます。', guideAction: 'すべてのガイドを見る'
  }),
  pl: compactLocale({
    name: 'Polish', nativeName: 'Polski', ogLocale: 'pl_PL', nav: { plan: 'Plan', features: 'Funkcje', guides: 'Poradniki', faq: 'FAQ', download: 'Pobierz aplikację' },
    hero: { badge: 'Monitor snu dziecka i plan AI', title: 'Wreszcie zrozum sen swojego dziecka.', body: 'Yorix poznaje rytm Twojego dziecka i zamienia drzemki, okna czuwania, karmienia, wzrost oraz codzienną opiekę w plan dopasowujący się do prawdziwego życia rodziny.', primary: 'Zaplanuj kolejną drzemkę', secondary: 'Czytaj poradniki snu' }, stats: ['języków', 'reklam w rutynie', 'coach AI'],
    proof: [{ title: 'Osobisty plan snu', body: 'Kolejna drzemka i pora snu dostosowują się, gdy dzień się zmienia.' }, { title: 'Coach snu AI 24/7', body: 'Pytaj o okna czuwania, krótkie drzemki i rutyny.' }, { title: 'Prywatność od początku', body: 'Twoje dane należą do Ciebie. Nie sprzedajemy danych osobowych.' }],
    plan: { eyebrow: 'Twoje dziecko ma plan', title: 'Od oznak zmęczenia do jasnego kolejnego kroku.', body: 'Yorix odpowiada na pytanie każdego zmęczonego rodzica: kiedy moje dziecko powinno spać dalej? Aplikacja śledzi dzień i zachowuje elastyczność planu.', steps: ['Zbuduj rutynę dla całej rodziny', 'Zapobiegaj przemęczeniu przed snem', 'Ucz się z prawdziwych wzorców snu i opieki'] },
    stories: ['Wiedz, kiedy dziecko powinno spać', 'Zobacz wzorce snu i wzrostu', 'Zapytaj, gdy nie masz siły szukać', 'Stwórz znajome środowisko snu'], storyBodies: ['Yorix dostosowuje plan, gdy dzień się zmienia', 'Codzienne wpisy stają się jasnymi tygodniowymi wnioskami', 'Uzyskaj pomoc przy krótkich drzemkach i nocnych pobudkach', 'Uspokajające dźwięki wspierają wieczorną rutynę'], sleepSounds: 'Biały szum i dźwięki natury',
    trust: { eyebrow: 'Dla zmęczonych rodziców', title: 'Mniej liczenia snu. Więcej pewności.', body: 'Yorix daje rodzinom spokojną strukturę bez zamieniania każdej drzemki, karmienia lub pieluchy w arkusz.', cards: [{ title: 'Mniej zgadywania', body: 'Łatwiej zrozumieć okna czuwania i kolejną dobrą porę snu.' }, { title: 'Wspólna pamięć', body: 'Oboje rodzice widzą te same dane opieki.' }, { title: 'Na prawdziwe noce', body: 'Szybkie zapisy, pomoc AI i dźwięki snu.' }] },
    faq: { eyebrow: 'FAQ', title: 'Pytania o sen dziecka, spokojnie wyjaśnione.', items: [{ question: 'Czym Yorix różni się od tabeli snu?', answer: 'Tabela pokazuje średnie. Yorix wykorzystuje rzeczywisty sen i rutynę dziecka, aby dostosować kolejne okno snu.' }, { question: 'Czy mogę używać Yorix z noworodkiem?', answer: 'Tak. Od początku Yorix jest prostym dziennikiem snu, karmienia, pieluch i opieki.' }, { question: 'Czy Yorix zastępuje poradę medyczną?', answer: 'Nie. Yorix pomaga w rutynie. W razie obaw zdrowotnych skontaktuj się z lekarzem.' }] },
    cta: { badge: 'Dla prawdziwego życia rodzinnego', title: 'Zacznij od jednej drzemki. Pozwól Yorix poznać rytm.', body: 'Śledź dzisiejszy sen, karmienia, pieluchy, wzrost i rutyny, aby jutro mieć jaśniejszy plan.', action: 'Pobierz Yorix' }, footer: 'Yorix jest pomocą w rutynie dla rodziców i nie zapewnia diagnozy medycznej ani porad nagłych.', guideBody: 'Szczegółowe poradniki są dostępne po angielsku.', guideAction: 'Zobacz wszystkie poradniki'
  }),
  cs: compactLocale({
    name: 'Czech', nativeName: 'Čeština', ogLocale: 'cs_CZ', nav: { plan: 'Plán', features: 'Funkce', guides: 'Průvodce', faq: 'FAQ', download: 'Stáhnout aplikaci' },
    hero: { badge: 'Sledování spánku miminka a AI plán', title: 'Konečně porozumějte spánku svého miminka.', body: 'Yorix se učí rytmus vašeho dítěte a mění denní spánky, okna bdění, krmení, růst a každodenní péči v plán, který se přizpůsobí skutečnému rodinnému životu.', primary: 'Naplánovat další spánek', secondary: 'Číst průvodce spánkem' }, stats: ['jazyků', 'reklam v rutině', 'AI kouč'],
    proof: [{ title: 'Osobní plán spánku', body: 'Další spánek a večerka se přizpůsobí, když se den změní.' }, { title: 'AI kouč spánku 24/7', body: 'Ptejte se na okna bdění, krátké spánky a rutiny.' }, { title: 'Soukromí na prvním místě', body: 'Vaše data jsou vaše. Osobní údaje neprodáváme.' }],
    plan: { eyebrow: 'Vaše miminko má plán', title: 'Od známek únavy k jasnému dalšímu kroku.', body: 'Yorix se soustředí na otázku každého unaveného rodiče: kdy by mělo miminko spát příště? Aplikace sleduje den a udržuje plán pružný.', steps: ['Vytvořte rutinu, která funguje pro všechny', 'Předcházejte přetažení před spaním', 'Učte se ze skutečných vzorců spánku a péče'] },
    stories: ['Vědět, kdy má miminko spát', 'Vidět vzorce spánku a růstu', 'Zeptat se, když nemáte sílu hledat', 'Vytvořit známé prostředí pro spánek'], storyBodies: ['Yorix upraví plán, když se den změní', 'Denní záznamy se změní v jasné týdenní poznatky', 'Pomoc s krátkými spánky a nočním buzením', 'Uklidňující zvuky podpoří večerní rutinu'], sleepSounds: 'Bílý šum a zvuky přírody',
    trust: { eyebrow: 'Pro unavené rodiče', title: 'Méně počítání spánku. Více jistoty.', body: 'Yorix dává rodinám klidnou strukturu bez toho, aby měnil každý spánek, krmení nebo plenku na tabulku.', cards: [{ title: 'Méně hádání', body: 'Snáze pochopíte okna bdění a další vhodný čas spánku.' }, { title: 'Sdílená paměť', body: 'Oba rodiče vidí stejná data o péči.' }, { title: 'Pro skutečné noci', body: 'Rychlé zápisy, pomoc AI a zvuky pro spánek.' }] },
    faq: { eyebrow: 'FAQ', title: 'Otázky o spánku miminka, klidně zodpovězené.', items: [{ question: 'Jak se Yorix liší od tabulky spánku?', answer: 'Tabulka ukazuje průměry. Yorix používá skutečný spánek a rutinu dítěte k úpravě dalšího okna spánku.' }, { question: 'Mohu používat Yorix s novorozencem?', answer: 'Ano. Od začátku je Yorix jednoduchý záznam spánku, krmení, plenek a péče.' }, { question: 'Nahrazuje Yorix lékařskou radu?', answer: 'Ne. Yorix je pomocník s rutinou. Při zdravotních obavách kontaktujte odborníka.' }] },
    cta: { badge: 'Pro skutečný rodinný život', title: 'Začněte jedním spánkem. Nechte Yorix poznat rytmus.', body: 'Sledujte dnešní spánek, krmení, plenky, růst a rutiny pro jasnější plán na zítra.', action: 'Stáhnout Yorix' }, footer: 'Yorix je pomocník s rutinou pro rodiče a neposkytuje zdravotní diagnózu ani akutní rady.', guideBody: 'Podrobní průvodci jsou k dispozici v angličtině.', guideAction: 'Zobrazit všechny průvodce'
  }),
  no: compactLocale({
    name: 'Norwegian', nativeName: 'Norsk', ogLocale: 'nb_NO', nav: { plan: 'Plan', features: 'Funksjoner', guides: 'Guider', faq: 'FAQ', download: 'Last ned appen' },
    hero: { badge: 'Babysøvnsporing og AI-plan', title: 'Forstå endelig babyens søvn.', body: 'Yorix lærer barnets rytme og gjør lurer, våkenvinduer, mating, vekst og daglig omsorg til en plan som tilpasser seg ekte familieliv.', primary: 'Planlegg neste lur', secondary: 'Les søvnguider' }, stats: ['språk', 'annonser i rutinen', 'AI-coach'],
    proof: [{ title: 'Personlig søvnplan', body: 'Neste lur og leggetid tilpasser seg når dagen endrer seg.' }, { title: 'AI-søvncoach hele døgnet', body: 'Spør om våkenvinduer, korte lurer og rutiner.' }, { title: 'Personvern først', body: 'Dataene dine er dine. Vi selger ikke personopplysninger.' }],
    plan: { eyebrow: 'Babyen din har en plan', title: 'Fra trøtthetstegn til et tydelig neste steg.', body: 'Yorix svarer på spørsmålet alle trøtte foreldre stiller: Når bør babyen min sove neste gang? Appen følger dagen og holder planen fleksibel.', steps: ['Bygg en rutine som fungerer for alle', 'Forebygg overtrøtthet før leggetid', 'Lær av ekte søvn- og omsorgsmønstre'] },
    stories: ['Vit når babyen bør sove neste gang', 'Se mønstre i søvn og vekst', 'Spør når du er for trøtt til å søke', 'Skap et kjent sovemiljø'], storyBodies: ['Yorix justerer planen når dagen endrer seg', 'Daglige logger blir tydelig ukentlig innsikt', 'Få hjelp med korte lurer og nattlige oppvåkninger', 'Beroligende lyder støtter kveldsrutinen'], sleepSounds: 'Hvit støy og naturlyder',
    trust: { eyebrow: 'For trøtte foreldre', title: 'Mindre søvnregning. Mer trygghet.', body: 'Yorix gir familien en rolig struktur uten å gjøre hver lur, mating eller bleie til et regneark.', cards: [{ title: 'Mindre gjetting', body: 'Forstå våkenvinduer og neste gode sovetid.' }, { title: 'Ett delt minne', body: 'Begge foreldre ser de samme omsorgsdataene.' }, { title: 'Laget for ekte netter', body: 'Rask logging, AI-hjelp og søvnlyder.' }] },
    faq: { eyebrow: 'FAQ', title: 'Spørsmål om babysøvn, rolig besvart.', items: [{ question: 'Hva gjør Yorix annerledes enn en søvntabell?', answer: 'En tabell viser gjennomsnitt. Yorix bruker babyens faktiske søvn og rutine for å justere neste søvnvindu.' }, { question: 'Kan jeg bruke Yorix med en nyfødt?', answer: 'Ja. Yorix er en enkel logg for søvn, mating, bleier og omsorg fra starten.' }, { question: 'Erstatter Yorix medisinske råd?', answer: 'Nei. Yorix er en rutinehjelp. Kontakt helsepersonell ved helsebekymringer.' }] },
    cta: { badge: 'For ekte familieliv', title: 'Start med én lur. La Yorix lære rytmen.', body: 'Følg dagens søvn, mating, bleier, vekst og rutiner og få en klarere plan for i morgen.', action: 'Last ned Yorix' }, footer: 'Yorix er en rutinehjelp for foreldre og gir ikke medisinsk diagnose eller akuttråd.', guideBody: 'Detaljerte guider er tilgjengelige på engelsk.', guideAction: 'Se alle guider'
  }),
  ar: compactLocale({
    name: 'Arabic', nativeName: 'العربية', ogLocale: 'ar', nav: { plan: 'الخطة', features: 'المزايا', guides: 'الأدلة', faq: 'الأسئلة', download: 'تنزيل التطبيق' },
    hero: { badge: 'متابعة نوم الطفل وخطة بالذكاء الاصطناعي', title: 'افهمي نوم طفلك أخيراً.', body: 'يتعلم Yorix إيقاع طفلك ويحوّل القيلولات وفترات اليقظة والرضعات والنمو والرعاية اليومية إلى خطة تتكيف مع حياة الأسرة الحقيقية.', primary: 'خططي للقيلولة التالية', secondary: 'اقرئي أدلة النوم' }, stats: ['لغة', 'إعلانات في روتينك', 'مدرب ذكاء اصطناعي'],
    proof: [{ title: 'خطة نوم شخصية', body: 'تتغير القيلولة التالية ووقت النوم حين يتغير اليوم.' }, { title: 'مدرب نوم بالذكاء الاصطناعي 24/7', body: 'اسألي عن فترات اليقظة والقيلولات القصيرة والروتين.' }, { title: 'الخصوصية أولاً', body: 'بياناتك ملكك. لا نبيع البيانات الشخصية.' }],
    plan: { eyebrow: 'لطفلك خطة', title: 'من إشارات النعاس إلى الخطوة التالية الواضحة.', body: 'يركز Yorix على سؤال كل والد مرهق: متى يجب أن ينام طفلي بعد ذلك؟ يتابع التطبيق اليوم ويحافظ على مرونة الخطة.', steps: ['ابني روتيناً يناسب الجميع', 'تجنبي الإرهاق قبل وقت النوم', 'تعلمي من أنماط النوم والرعاية الحقيقية'] },
    stories: ['اعرفي متى يجب أن ينام طفلك', 'شاهدي أنماط النوم والنمو', 'اسألي حين تكونين متعبة من البحث', 'اصنعي بيئة نوم مألوفة'], storyBodies: ['يعدل Yorix الخطة حين يتغير اليوم', 'تتحول السجلات اليومية إلى رؤى أسبوعية واضحة', 'احصلي على مساعدة مع القيلولات القصيرة والاستيقاظ الليلي', 'الأصوات الهادئة تدعم روتين المساء'], sleepSounds: 'الضوضاء البيضاء وأصوات الطبيعة',
    trust: { eyebrow: 'للوالدين المتعبين', title: 'حسابات نوم أقل. ثقة أكبر.', body: 'يمنح Yorix الأسر هيكلاً هادئاً من دون تحويل كل قيلولة أو رضعة أو حفاض إلى جدول بيانات.', cards: [{ title: 'تخمين أقل', body: 'افهمي فترات اليقظة ووقت النوم المناسب التالي.' }, { title: 'ذاكرة مشتركة', body: 'يرى الوالدان بيانات الرعاية نفسها.' }, { title: 'لليالي الحقيقية', body: 'تسجيل سريع ومساعدة بالذكاء الاصطناعي وأصوات للنوم.' }] },
    faq: { eyebrow: 'الأسئلة الشائعة', title: 'أسئلة عن نوم الطفل، بإجابات هادئة.', items: [{ question: 'بماذا يختلف Yorix عن جدول النوم؟', answer: 'يعرض الجدول المتوسطات. يستخدم Yorix نوم طفلك وروتينه الفعلي لتعديل نافذة النوم التالية.' }, { question: 'هل يمكن استخدام Yorix مع حديث الولادة؟', answer: 'نعم. Yorix سجل بسيط للنوم والرضعات والحفاضات والرعاية من البداية.' }, { question: 'هل يحل Yorix محل النصيحة الطبية؟', answer: 'لا. Yorix مساعد للروتين. تواصلي مع مختص صحي عند وجود قلق صحي.' }] },
    cta: { badge: 'للحياة الأسرية الحقيقية', title: 'ابدئي بقيلولة واحدة. دعي Yorix يتعلم الإيقاع.', body: 'تابعي نوم اليوم والرضعات والحفاضات والنمو والروتين لتحصلي على خطة أوضح للغد.', action: 'تنزيل Yorix' }, footer: 'Yorix مساعد للروتين للوالدين ولا يقدم تشخيصاً طبياً أو نصيحة طارئة.', guideBody: 'الأدلة التفصيلية متاحة باللغة الإنجليزية.', guideAction: 'عرض كل الأدلة'
  }),
  da: compactLocale({
    name: 'Danish', nativeName: 'Dansk', ogLocale: 'da_DK', nav: { plan: 'Plan', features: 'Funktioner', guides: 'Guider', faq: 'FAQ', download: 'Hent appen' },
    hero: { badge: 'Babysøvntracker og AI-plan', title: 'Forstå endelig dit barns søvn.', body: 'Yorix lærer dit barns rytme og gør lure, vågenvinduer, madning, vækst og daglig pleje til en plan, der tilpasser sig det virkelige familieliv.', primary: 'Planlæg næste lur', secondary: 'Læs søvnguides' }, stats: ['sprog', 'annoncer i din rutine', 'AI-coach'],
    proof: [{ title: 'Personlig søvnplan', body: 'Næste lur og sengetid tilpasser sig, når dagen ændrer sig.' }, { title: 'AI-søvncoach døgnet rundt', body: 'Spørg om vågenvinduer, korte lure og rutiner.' }, { title: 'Privatliv først', body: 'Dine data er dine. Vi sælger ikke personoplysninger.' }],
    plan: { eyebrow: 'Dit barn har en plan', title: 'Fra træthedstegn til et klart næste skridt.', body: 'Yorix svarer på spørgsmålet, alle trætte forældre stiller: hvornår bør mit barn sove næste gang? Appen følger dagen og holder planen fleksibel.', steps: ['Byg en rutine, der virker for alle', 'Forebyg overtræthed før sengetid', 'Lær af virkelige søvn- og plejemønstre'] },
    stories: ['Vid hvornår barnet skal sove næste gang', 'Se mønstre i søvn og vækst', 'Spørg når du er for træt til at søge', 'Skab et velkendt sovemiljø'], storyBodies: ['Yorix justerer planen, når dagen ændrer sig', 'Daglige registreringer bliver klare ugentlige indsigter', 'Få hjælp til korte lure og natlige opvågninger', 'Beroligende lyde støtter aftenrutinen'], sleepSounds: 'Hvid støj og naturlyde',
    trust: { eyebrow: 'For trætte forældre', title: 'Mindre søvnregning. Mere tryghed.', body: 'Yorix giver familien rolig struktur uden at gøre hver lur, måltid eller ble til et regneark.', cards: [{ title: 'Mindre gætteri', body: 'Forstå vågenvinduer og det næste gode sovetidspunkt.' }, { title: 'En fælles hukommelse', body: 'Begge forældre ser de samme plejedata.' }, { title: 'Lavet til rigtige nætter', body: 'Hurtig registrering, AI-hjælp og søvnlyde.' }] },
    faq: { eyebrow: 'FAQ', title: 'Spørgsmål om babysøvn, roligt besvaret.', items: [{ question: 'Hvad gør Yorix anderledes end en søvntabel?', answer: 'En tabel viser gennemsnit. Yorix bruger dit barns faktiske søvn og rutine til at tilpasse næste søvnvindue.' }, { question: 'Kan jeg bruge Yorix med en nyfødt?', answer: 'Ja. Yorix er en enkel log over søvn, madning, bleer og pleje fra starten.' }, { question: 'Erstatter Yorix lægelig rådgivning?', answer: 'Nej. Yorix er en rutinehjælp. Kontakt sundhedsfagligt personale ved helbredsbekymringer.' }] },
    cta: { badge: 'Til det virkelige familieliv', title: 'Start med én lur. Lad Yorix lære rytmen.', body: 'Følg dagens søvn, måltider, bleer, vækst og rutiner og få en klarere plan for i morgen.', action: 'Hent Yorix' }, footer: 'Yorix er en rutinehjælp til forældre og giver ikke medicinsk diagnose eller akutrådgivning.', guideBody: 'Detaljerede guider er tilgængelige på engelsk.', guideAction: 'Se alle guider'
  }),
  he: compactLocale({
    name: 'Hebrew', nativeName: 'עברית', ogLocale: 'he_IL', nav: { plan: 'תוכנית', features: 'יכולות', guides: 'מדריכים', faq: 'שאלות', download: 'הורדת האפליקציה' },
    hero: { badge: 'מעקב שינת תינוק ותוכנית AI', title: 'סוף סוף להבין את השינה של התינוק.', body: 'Yorix לומדת את הקצב של הילד והופכת תנומות, חלונות ערות, האכלה, גדילה וטיפול יומיומי לתוכנית שמסתגלת לחיי המשפחה האמיתיים.', primary: 'תכנון התנומה הבאה', secondary: 'קריאת מדריכי שינה' }, stats: ['שפות', 'פרסומות בשגרה', 'מאמן AI'],
    proof: [{ title: 'תוכנית שינה אישית', body: 'התנומה הבאה ושעת השינה מסתגלות כשהיום משתנה.' }, { title: 'מאמן שינה AI 24/7', body: 'אפשר לשאול על חלונות ערות, תנומות קצרות ושגרה.' }, { title: 'פרטיות תחילה', body: 'הנתונים שלך שייכים לך. אנחנו לא מוכרים מידע אישי.' }],
    plan: { eyebrow: 'לתינוק יש תוכנית', title: 'מסימני עייפות לצעד הבא והברור.', body: 'Yorix עונה על השאלה של כל הורה עייף: מתי התינוק צריך לישון שוב? האפליקציה עוקבת אחרי היום ושומרת על גמישות התוכנית.', steps: ['לבנות שגרה שמתאימה לכולם', 'למנוע עייפות יתר לפני השינה', 'ללמוד מדפוסי שינה וטיפול אמיתיים'] },
    stories: ['לדעת מתי התינוק צריך לישון', 'לראות דפוסי שינה וגדילה', 'לשאול כשעייפים מדי לחפש', 'ליצור סביבת שינה מוכרת'], storyBodies: ['Yorix מתאימה את התוכנית כשהיום משתנה', 'רישומים יומיים הופכים לתובנות שבועיות ברורות', 'קבלו עזרה עם תנומות קצרות ויקיצות לילה', 'צלילים מרגיעים תומכים בשגרת הערב'], sleepSounds: 'רעש לבן וצלילי טבע',
    trust: { eyebrow: 'להורים עייפים', title: 'פחות חישובי שינה. יותר ביטחון.', body: 'Yorix נותנת למשפחות מבנה רגוע בלי להפוך כל תנומה, ארוחה או חיתול לגיליון נתונים.', cards: [{ title: 'פחות ניחושים', body: 'להבין חלונות ערות ואת זמן השינה הבא.' }, { title: 'זיכרון משותף', body: 'שני ההורים רואים את אותם נתוני טיפול.' }, { title: 'ללילות אמיתיים', body: 'רישום מהיר, עזרת AI וצלילי שינה.' }] },
    faq: { eyebrow: 'שאלות נפוצות', title: 'שאלות על שינת תינוק, עם תשובות רגועות.', items: [{ question: 'במה Yorix שונה מטבלת שינה?', answer: 'טבלה מציגה ממוצעים. Yorix משתמשת בשינה ובשגרה האמיתיות של התינוק כדי להתאים את חלון השינה הבא.' }, { question: 'אפשר להשתמש ב-Yorix עם תינוק בן יומו?', answer: 'כן. Yorix היא יומן פשוט לשינה, האכלה, חיתולים וטיפול מההתחלה.' }, { question: 'האם Yorix מחליפה ייעוץ רפואי?', answer: 'לא. Yorix היא עזרה לשגרה. פנו לאיש מקצוע רפואי במקרה של דאגה בריאותית.' }] },
    cta: { badge: 'לחיי משפחה אמיתיים', title: 'מתחילים בתנומה אחת. נותנים ל-Yorix ללמוד את הקצב.', body: 'עקבו אחר השינה, ההאכלה, החיתולים, הגדילה והשגרה של היום וקבלו תוכנית ברורה יותר למחר.', action: 'הורדת Yorix' }, footer: 'Yorix היא עזרה לשגרה להורים ואינה מספקת אבחון רפואי או ייעוץ חירום.', guideBody: 'מדריכים מפורטים זמינים באנגלית.', guideAction: 'לכל המדריכים'
  }),
  uk: compactLocale({
    name: 'Ukrainian', nativeName: 'Українська', ogLocale: 'uk_UA', nav: { plan: 'План', features: 'Можливості', guides: 'Гайди', faq: 'Запитання', download: 'Завантажити застосунок' },
    hero: { badge: 'Трекер сну малюка та планувальник з ШІ', title: 'Нарешті зрозумійте сон вашої дитини.', body: 'Yorix вивчає ритм вашої дитини й перетворює денний сон, вікна неспання, годування, ріст і щоденний догляд на план, що адаптується до реального життя родини.', primary: 'Спланувати наступний сон', secondary: 'Читати гайди про сон' }, stats: ['мов', 'реклами у вашій рутині', 'ШІ-коуч'],
    proof: [{ title: 'Персональний план сну', body: 'Наступний сон і час відбою змінюються разом із днем.' }, { title: 'ШІ-коуч зі сну 24/7', body: 'Запитуйте про вікна неспання, короткі сни та рутину.' }, { title: 'Приватність за задумом', body: 'Ваші дані належать вам. Ми не продаємо персональні дані.' }],
    plan: { eyebrow: 'У вашої дитини є план', title: 'Від ознак втоми до зрозумілого наступного кроку.', body: 'Yorix відповідає на запитання кожного втомленого з батьків: коли дитині час спати далі? Застосунок стежить за днем і зберігає гнучкість плану.', steps: ['Створіть рутину для всієї родини', 'Запобігайте перевтомі перед сном', 'Вчіться на реальних патернах сну й догляду'] },
    stories: ['Знайте, коли дитині час спати', 'Бачте патерни сну й росту', 'Запитайте, коли немає сил шукати', 'Створіть знайоме середовище для сну'], storyBodies: ['Yorix оновлює план, коли день змінюється', 'Щоденні записи стають зрозумілими тижневими висновками', 'Отримуйте допомогу з короткими снами та нічними пробудженнями', 'Заспокійливі звуки підтримують вечірню рутину'], sleepSounds: 'Білий шум і звуки природи',
    trust: { eyebrow: 'Для втомлених батьків', title: 'Менше математики сну. Більше впевненості.', body: 'Yorix дає родинам спокійну структуру, не перетворюючи кожен сон, годування чи підгузок на таблицю.', cards: [{ title: 'Менше здогадок', body: 'Легше зрозуміти вікна неспання і наступний вдалий час для сну.' }, { title: 'Спільна пам’ять', body: 'Обоє батьків бачать одні й ті самі дані догляду.' }, { title: 'Для справжніх ночей', body: 'Швидкі записи, допомога ШІ та звуки для сну.' }] },
    faq: { eyebrow: 'Запитання', title: 'Питання про сон малюка, зі спокійними відповідями.', items: [{ question: 'Чим Yorix відрізняється від таблиці сну?', answer: 'Таблиця дає середні значення. Yorix використовує реальний сон і рутину дитини, щоб адаптувати наступне вікно сну.' }, { question: 'Чи можна користуватися Yorix із новонародженим?', answer: 'Так. Yorix від початку є простим журналом сну, годувань, підгузків і догляду.' }, { question: 'Чи замінює Yorix медичну пораду?', answer: 'Ні. Yorix допомагає з рутиною. За питань здоров’я зверніться до фахівця.' }] },
    cta: { badge: 'Для реального життя родини', title: 'Почніть з одного сну. Нехай Yorix вивчить ритм.', body: 'Відстежуйте сьогоднішній сон, годування, підгузки, ріст і рутину, щоб отримати чіткіший план на завтра.', action: 'Завантажити Yorix' }, footer: 'Yorix — помічник із рутиною для батьків, а не медична діагностика чи екстрена порада.', guideBody: 'Детальні гайди доступні англійською.', guideAction: 'Переглянути всі гайди'
  }),
  vi: compactLocale({
    name: 'Vietnamese', nativeName: 'Tiếng Việt', ogLocale: 'vi_VN', nav: { plan: 'Kế hoạch', features: 'Tính năng', guides: 'Hướng dẫn', faq: 'Câu hỏi', download: 'Tải ứng dụng' },
    hero: { badge: 'Theo dõi giấc ngủ bé và lịch AI', title: 'Cuối cùng cũng hiểu giấc ngủ của bé.', body: 'Yorix học nhịp điệu của con bạn và biến các giấc ngủ ngắn, thời gian thức, bú ăn, tăng trưởng và chăm sóc hằng ngày thành kế hoạch phù hợp với cuộc sống gia đình thực tế.', primary: 'Lên kế hoạch giấc ngủ tiếp theo', secondary: 'Đọc hướng dẫn về giấc ngủ' }, stats: ['ngôn ngữ', 'quảng cáo trong thói quen', 'huấn luyện viên AI'],
    proof: [{ title: 'Kế hoạch ngủ cá nhân', body: 'Giấc ngủ tiếp theo và giờ đi ngủ thay đổi khi ngày mới thay đổi.' }, { title: 'Huấn luyện viên ngủ AI 24/7', body: 'Hỏi về thời gian thức, giấc ngủ ngắn và thói quen.' }, { title: 'Quyền riêng tư trước hết', body: 'Dữ liệu là của bạn. Chúng tôi không bán dữ liệu cá nhân.' }],
    plan: { eyebrow: 'Bé có một kế hoạch', title: 'Từ dấu hiệu buồn ngủ đến bước tiếp theo rõ ràng.', body: 'Yorix tập trung vào câu hỏi của mọi cha mẹ mệt mỏi: khi nào bé nên ngủ tiếp? Ứng dụng theo dõi cả ngày và giữ kế hoạch linh hoạt.', steps: ['Xây dựng thói quen phù hợp với mọi người', 'Ngăn bé quá mệt trước giờ ngủ', 'Học từ nhịp ngủ và chăm sóc thực tế'] },
    stories: ['Biết khi nào bé cần ngủ tiếp', 'Thấy các mẫu ngủ và tăng trưởng', 'Hỏi khi quá mệt để tìm kiếm', 'Tạo môi trường ngủ quen thuộc'], storyBodies: ['Yorix điều chỉnh kế hoạch khi ngày thay đổi', 'Nhật ký hằng ngày trở thành thông tin rõ ràng theo tuần', 'Nhận hỗ trợ với giấc ngủ ngắn và thức giấc ban đêm', 'Âm thanh dịu nhẹ hỗ trợ thói quen buổi tối'], sleepSounds: 'Tiếng ồn trắng và âm thanh thiên nhiên',
    trust: { eyebrow: 'Dành cho cha mẹ mệt mỏi', title: 'Ít tính toán giấc ngủ. Nhiều tự tin hơn.', body: 'Yorix mang đến cấu trúc bình tĩnh cho gia đình mà không biến mỗi giấc ngủ, cữ ăn hay tã thành bảng tính.', cards: [{ title: 'Ít đoán hơn', body: 'Hiểu thời gian thức và thời điểm ngủ tốt tiếp theo.' }, { title: 'Một ký ức chung', body: 'Cả hai cha mẹ đều thấy cùng dữ liệu chăm sóc.' }, { title: 'Dành cho những đêm thực tế', body: 'Ghi nhanh, hỗ trợ AI và âm thanh ngủ.' }] },
    faq: { eyebrow: 'Câu hỏi thường gặp', title: 'Câu hỏi về giấc ngủ của bé, được trả lời nhẹ nhàng.', items: [{ question: 'Yorix khác gì bảng giờ ngủ?', answer: 'Bảng chỉ cho mức trung bình. Yorix dùng giấc ngủ và thói quen thực tế của bé để điều chỉnh khung giờ ngủ tiếp theo.' }, { question: 'Có thể dùng Yorix cho trẻ sơ sinh không?', answer: 'Có. Yorix là nhật ký đơn giản về giấc ngủ, bú ăn, tã và chăm sóc từ đầu.' }, { question: 'Yorix có thay thế tư vấn y tế không?', answer: 'Không. Yorix hỗ trợ thói quen. Hãy liên hệ chuyên gia y tế khi lo ngại sức khỏe.' }] },
    cta: { badge: 'Cho cuộc sống gia đình thực tế', title: 'Bắt đầu với một giấc ngủ. Hãy để Yorix học nhịp điệu.', body: 'Theo dõi giấc ngủ, bú ăn, tã, tăng trưởng và thói quen hôm nay để có kế hoạch rõ ràng hơn cho ngày mai.', action: 'Tải Yorix' }, footer: 'Yorix là công cụ hỗ trợ thói quen cho cha mẹ, không cung cấp chẩn đoán y tế hay tư vấn khẩn cấp.', guideBody: 'Hướng dẫn chi tiết hiện có bằng tiếng Anh.', guideAction: 'Xem tất cả hướng dẫn'
  }),
  ms: compactLocale({
    name: 'Malay', nativeName: 'Bahasa Melayu', ogLocale: 'ms_MY', nav: { plan: 'Pelan', features: 'Ciri', guides: 'Panduan', faq: 'FAQ', download: 'Muat turun aplikasi' },
    hero: { badge: 'Penjejak tidur bayi dan pelan AI', title: 'Akhirnya fahami tidur bayi anda.', body: 'Yorix mempelajari rentak anak anda dan mengubah tidur siang, waktu berjaga, penyusuan, tumbesaran dan penjagaan harian menjadi pelan yang menyesuaikan diri dengan kehidupan keluarga sebenar.', primary: 'Rancang tidur seterusnya', secondary: 'Baca panduan tidur' }, stats: ['bahasa', 'iklan dalam rutin', 'jurulatih AI'],
    proof: [{ title: 'Pelan tidur peribadi', body: 'Tidur seterusnya dan waktu malam berubah apabila hari berubah.' }, { title: 'Jurulatih tidur AI 24/7', body: 'Tanya tentang waktu berjaga, tidur singkat dan rutin.' }, { title: 'Privasi diutamakan', body: 'Data anda milik anda. Kami tidak menjual data peribadi.' }],
    plan: { eyebrow: 'Bayi anda ada pelan', title: 'Daripada tanda mengantuk kepada langkah seterusnya yang jelas.', body: 'Yorix menjawab soalan setiap ibu bapa yang letih: bila bayi saya perlu tidur lagi? Aplikasi mengikuti hari anda dan mengekalkan pelan yang fleksibel.', steps: ['Bina rutin yang sesuai untuk semua', 'Cegah terlalu letih sebelum tidur', 'Belajar daripada pola tidur dan penjagaan sebenar'] },
    stories: ['Tahu bila bayi perlu tidur lagi', 'Lihat pola tidur dan tumbesaran', 'Tanya apabila terlalu letih untuk mencari', 'Cipta suasana tidur yang biasa'], storyBodies: ['Yorix melaras pelan apabila hari berubah', 'Log harian menjadi pandangan mingguan yang jelas', 'Dapatkan bantuan untuk tidur singkat dan terjaga malam', 'Bunyi menenangkan menyokong rutin malam'], sleepSounds: 'Bunyi putih dan bunyi alam',
    trust: { eyebrow: 'Untuk ibu bapa yang letih', title: 'Kurang mengira tidur. Lebih yakin.', body: 'Yorix memberi keluarga struktur yang tenang tanpa menjadikan setiap tidur, makan atau lampin sebagai hamparan data.', cards: [{ title: 'Kurang meneka', body: 'Fahami waktu berjaga dan masa tidur baik seterusnya.' }, { title: 'Satu ingatan bersama', body: 'Kedua-dua ibu bapa melihat data penjagaan yang sama.' }, { title: 'Untuk malam yang sebenar', body: 'Catatan cepat, bantuan AI dan bunyi tidur.' }] },
    faq: { eyebrow: 'FAQ', title: 'Soalan tidur bayi, dijawab dengan tenang.', items: [{ question: 'Apakah beza Yorix dengan jadual tidur?', answer: 'Jadual memberi purata. Yorix menggunakan tidur dan rutin sebenar bayi untuk melaras tetingkap tidur seterusnya.' }, { question: 'Bolehkah saya guna Yorix untuk bayi baru lahir?', answer: 'Ya. Yorix ialah log mudah untuk tidur, penyusuan, lampin dan penjagaan sejak awal.' }, { question: 'Adakah Yorix menggantikan nasihat perubatan?', answer: 'Tidak. Yorix membantu rutin. Hubungi profesional kesihatan jika ada kebimbangan.' }] },
    cta: { badge: 'Untuk kehidupan keluarga sebenar', title: 'Mulakan dengan satu tidur. Biarkan Yorix belajar rentaknya.', body: 'Jejak tidur, penyusuan, lampin, tumbesaran dan rutin hari ini untuk pelan yang lebih jelas esok.', action: 'Muat turun Yorix' }, footer: 'Yorix ialah bantuan rutin untuk ibu bapa dan tidak memberi diagnosis perubatan atau nasihat kecemasan.', guideBody: 'Panduan terperinci tersedia dalam bahasa Inggeris.', guideAction: 'Lihat semua panduan'
  }),
  hi: compactLocale({
    name: 'Hindi', nativeName: 'हिन्दी', ogLocale: 'hi_IN', nav: { plan: 'योजना', features: 'विशेषताएँ', guides: 'गाइड', faq: 'सवाल', download: 'ऐप डाउनलोड करें' },
    hero: { badge: 'बेबी स्लीप ट्रैकर और AI शेड्यूल', title: 'आखिरकार अपने बच्चे की नींद को समझें।', body: 'Yorix आपके बच्चे की लय सीखता है और झपकियों, जागने के समय, फीडिंग, विकास और रोज़ की देखभाल को एक ऐसी योजना में बदलता है जो परिवार की असली जिंदगी के साथ बदलती है।', primary: 'अगली झपकी की योजना बनाएं', secondary: 'नींद की गाइड पढ़ें' }, stats: ['भाषाएँ', 'आपकी दिनचर्या में विज्ञापन', 'AI कोच'],
    proof: [{ title: 'व्यक्तिगत नींद योजना', body: 'अगली झपकी और सोने का समय दिन बदलने पर बदल जाते हैं।' }, { title: '24/7 AI स्लीप कोच', body: 'जागने के समय, छोटी झपकियों और दिनचर्या के बारे में पूछें।' }, { title: 'गोपनीयता पहले', body: 'आपका डेटा आपका है। हम निजी डेटा नहीं बेचते।' }],
    plan: { eyebrow: 'आपके बच्चे की एक योजना है', title: 'नींद के संकेतों से अगले स्पष्ट कदम तक।', body: 'Yorix हर थके हुए माता-पिता के सवाल पर केंद्रित है: मेरा बच्चा अगली बार कब सोए? ऐप दिन का साथ देता है और योजना को लचीला रखता है।', steps: ['ऐसी दिनचर्या बनाएं जो सबके लिए काम करे', 'सोने से पहले ज़्यादा थकान रोकें', 'नींद और देखभाल के वास्तविक पैटर्न से सीखें'] },
    stories: ['जानें कि बच्चा अगली बार कब सोए', 'नींद और विकास के पैटर्न देखें', 'जब खोजने की ऊर्जा न हो तब पूछें', 'परिचित नींद का माहौल बनाएं'], storyBodies: ['दिन बदलने पर Yorix योजना बदलता है', 'रोज़ के लॉग स्पष्ट साप्ताहिक जानकारी बन जाते हैं', 'छोटी झपकियों और रात में जागने में मदद पाएं', 'सुकून देने वाली आवाज़ें शाम की दिनचर्या को सहारा देती हैं'], sleepSounds: 'व्हाइट नॉइज़ और प्रकृति की आवाज़ें',
    trust: { eyebrow: 'थके हुए माता-पिता के लिए', title: 'नींद की कम गणना। ज्यादा भरोसा।', body: 'Yorix हर झपकी, फीड या डायपर को स्प्रेडशीट बनाए बिना परिवारों को शांत संरचना देता है।', cards: [{ title: 'कम अंदाज़े', body: 'जागने के समय और अगले अच्छे नींद के समय को समझें।' }, { title: 'साझा याददाश्त', body: 'दोनों माता-पिता एक ही देखभाल डेटा देखते हैं।' }, { title: 'असली रातों के लिए', body: 'तेज़ लॉगिंग, AI मदद और नींद की आवाज़ें।' }] },
    faq: { eyebrow: 'अक्सर पूछे जाने वाले सवाल', title: 'बच्चे की नींद के सवाल, शांति से जवाब।', items: [{ question: 'Yorix नींद चार्ट से कैसे अलग है?', answer: 'चार्ट औसत दिखाता है। Yorix बच्चे की असली नींद और दिनचर्या से अगली नींद की अवधि समायोजित करता है।' }, { question: 'क्या नवजात के साथ Yorix इस्तेमाल कर सकता हूँ?', answer: 'हाँ। शुरू से ही Yorix नींद, फीडिंग, डायपर और देखभाल का आसान लॉग है।' }, { question: 'क्या Yorix चिकित्सकीय सलाह की जगह लेता है?', answer: 'नहीं। Yorix दिनचर्या सहायक है। स्वास्थ्य चिंता होने पर योग्य विशेषज्ञ से संपर्क करें।' }] },
    cta: { badge: 'असली पारिवारिक जीवन के लिए', title: 'एक झपकी से शुरू करें। Yorix को लय सीखने दें।', body: 'आज की नींद, फीडिंग, डायपर, विकास और दिनचर्या ट्रैक करें और कल के लिए स्पष्ट योजना पाएं।', action: 'Yorix डाउनलोड करें' }, footer: 'Yorix माता-पिता के लिए दिनचर्या सहायक है और चिकित्सकीय निदान या आपात सलाह नहीं देता।', guideBody: 'विस्तृत गाइड अंग्रेज़ी में उपलब्ध हैं।', guideAction: 'सभी गाइड देखें'
  }),
});

export function isLocale(value: string): value is Locale {
  return locales.includes(value as Locale);
}

export function localeAlternates(path = '') {
  return Object.fromEntries(
    locales.map((locale) => [locale, `/${locale}${path}`]),
  );
}
