// GENERATED by CloudflareWorker/scripts/syncSitePrices.ts — do not edit by hand.
//
// Every price on this site comes from the worker's src/web/plans.ts, which is
// the single source of truth: it is what the acquirer is actually asked to
// charge. Change a price there and run `npm run sync:site-prices` in
// CloudflareWorker — the worker's `npm test` fails while this file is stale.
import type { WebCurrency } from './currency';

export type PlanId = 'week' | 'month' | 'year';

export type Plan = {
  id: PlanId;
  days: number;
  priceByn: number;
};

export const plans: Plan[] = [
  { id: 'week', days: 7, priceByn: 11.9 },
  { id: 'month', days: 30, priceByn: 23.9 },
  { id: 'year', days: 365, priceByn: 119.9 },
];

// What the buyer sees, in their own region's currency — the App Store price,
// so the web never looks dearer than the store they could have used instead.
export const prices: Record<PlanId, Record<WebCurrency, number>> = {
  week: { BYN: 11.9, RUB: 299 },
  month: { BYN: 23.9, RUB: 599 },
  year: { BYN: 119.9, RUB: 2990 },
};

// What a Belarusian-ruble acquirer charges for that price. The receipt says
// this number, so the page says it too before the buyer leaves.
export const charges: Record<PlanId, Record<WebCurrency, number>> = {
  week: { BYN: 11.9, RUB: 10.5 },
  month: { BYN: 23.9, RUB: 21 },
  year: { BYN: 119.9, RUB: 104.9 },
};

// The same, in roubles, for ЮKassa. A Russian buyer is charged the rouble
// price they were shown; a Belarusian one pays the Belarusian price converted
// at the same rate, so roubles never undercut it.
export const chargesRub: Record<PlanId, Record<WebCurrency, number>> = {
  week: { BYN: 339, RUB: 299 },
  month: { BYN: 681, RUB: 599 },
  year: { BYN: 3414, RUB: 2990 },
};
