// GENERATED by CloudflareWorker/scripts/syncSitePrices.ts — do not edit by hand.
//
// Every price on this site comes from the worker's src/web/plans.ts, which is
// the single source of truth: it is what the acquirer is actually asked to
// charge. Change a price there and run `npm run sync:site-prices` in
// CloudflareWorker — the worker's `npm test` fails while this file is stale.
import type { WebCurrency } from './currency';

export type PlanId = 'week' | 'month' | 'year';

export type Plan = {
  id: PlanId;
  days: number;
  priceByn: number;
};

export const plans: Plan[] = [
  { id: 'week', days: 7, priceByn: 11.9 },
  { id: 'month', days: 30, priceByn: 23.9 },
  { id: 'year', days: 365, priceByn: 119.9 },
];

// The App Store price of each region, in that region's own currency: the
// ceiling the tables below are kept under, so the web never looks dearer than
// the store the same parent could have bought from. Not a price to print —
// use chargeFor() in merchant.ts, which returns the money the buyer actually
// pays, in the currency their receipt will name.
export const prices: Record<PlanId, Record<WebCurrency, number>> = {
  week: { BYN: 11.9, RUB: 499 },
  month: { BYN: 23.9, RUB: 999 },
  year: { BYN: 119.9, RUB: 3990 },
};

// What each region pays when the acquirer settles in Belarusian rubles.
export const charges: Record<PlanId, Record<WebCurrency, number>> = {
  week: { BYN: 11.9, RUB: 17.94 },
  month: { BYN: 23.9, RUB: 35.92 },
  year: { BYN: 119.9, RUB: 143.47 },
};

// The same, in roubles, for ЮKassa. Belarus keeps its own row: its App Store
// tier is the cheaper one ($3.99 a week against Russia's 499 ₽), so pricing a
// Belarusian parent off the rouble list would charge them about half again
// what the store asks.
export const chargesRub: Record<PlanId, Record<WebCurrency, number>> = {
  week: { BYN: 329, RUB: 499 },
  month: { BYN: 659, RUB: 999 },
  year: { BYN: 3290, RUB: 3990 },
};
